"""
Django settings for ROMAN_PR project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
import warnings
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Подгружаем .env из корня проекта ДО любого os.getenv() — иначе HF_TOKEN,
# ANTHROPIC_API_KEY, SECRET_KEY и прочие переменные не подхватятся.
# .env уже в .gitignore — секреты не попадут в репозиторий.
# Если python-dotenv не установлен — пропускаем, переменные нужно задавать руками.
try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / '.env', override=False)
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on', 'dev', 'debug'}


def env_list(name, default):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(',') if item.strip()]


IS_TESTING = 'test' in sys.argv or 'pytest' in sys.argv[0].lower() or any('pytest' in a for a in sys.argv)

DEFAULT_INSECURE_SECRET_KEY = 'django-insecure-local-development-key-change-me'
SECRET_KEY = os.getenv('SECRET_KEY', DEFAULT_INSECURE_SECRET_KEY)

DEBUG = env_bool('DEBUG', True)
ALLOW_MOCK_SSO = env_bool('ALLOW_MOCK_SSO', DEBUG or IS_TESTING)
SKIP_OPTIONAL_APP_PROBES = env_bool('DOLG_SKIP_OPTIONAL_APP_PROBES', False)
SKIP_SOCIALACCOUNT_PROVIDERS = env_bool('DOLG_SKIP_SOCIALACCOUNT_PROVIDERS', False)

ALLOWED_HOSTS = env_list(
    'ALLOWED_HOSTS',
    # .localhost — wildcard для всех субдоменов localhost (dolg.localhost, shop.localhost и т.п.)
    # Современные браузеры резолвят *.localhost в 127.0.0.1 без hosts-файла (RFC 6761).
    # .local оставлен как опциональный fallback (требует правки hosts).
    # .trycloudflare.com — домены Cloudflare Quick Tunnel (для демо публичного доступа).
    # .ngrok-free.app / .ngrok.io — ngrok (на случай переключения туннеля).
    'localhost,127.0.0.1,[::1],.localhost,dolg.local,shop.dolg.local,www.dolg.local,'
    '.trycloudflare.com,.ngrok-free.app,.ngrok.io',
)

# CSRF trusted origins — Django 4.0+ требует явно перечислить источники
# для POST-запросов с https/non-default домена.
CSRF_TRUSTED_ORIGINS = env_list(
    'CSRF_TRUSTED_ORIGINS', 'https://*.trycloudflare.com,https://*.ngrok-free.app,https://*.ngrok.io'
)

if not DEBUG and SECRET_KEY == DEFAULT_INSECURE_SECRET_KEY and not IS_TESTING:
    warnings.warn(
        'SECRET_KEY is not set while DEBUG is disabled. Use .env.example as a template '
        'and set a unique SECRET_KEY before production/demo deployment.',
        RuntimeWarning,
    )

if not DEBUG and not ALLOWED_HOSTS and not IS_TESTING:
    warnings.warn(
        'ALLOWED_HOSTS is empty while DEBUG is disabled. Set ALLOWED_HOSTS before deployment.',
        RuntimeWarning,
    )

EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend'
    if DEBUG
    else 'django.core.mail.backends.smtp.EmailBackend',
)
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'DOLG <noreply@dolg.local>')


# Application definition

INSTALLED_APPS = [
    # daphne ДО django.contrib.staticfiles — Django requirement для ASGI.
    # daphne подменяет runserver на ASGI-сервер, что даёт WebSocket-поддержку
    # в dev-режиме без отдельного процесса. В production — отдельный daphne/uvicorn.
    #
    # 2026-06-05 startup-perf: daphne+channels+twisted+autobahn = ~4.5 сек на
    # eager import. Если запускаем CLI-команды (migrate, shell, check, test) —
    # WebSocket НЕ нужен. Skip через `DOLG_SKIP_ASGI=1` для batch-задач.
    *(['daphne'] if not os.getenv('DOLG_SKIP_ASGI') else []),
    'Dolg_APP',
    'shop',
    'accounts',
    'orders',
    'knowledge',
    'moderation',
    *(['channels'] if not os.getenv('DOLG_SKIP_ASGI') else []),
    # 2FA через django-otp: TOTPDevice (Google Authenticator / Authy / 1Password).
    # Enforcement по org-policy require_2fa — см. Dolg_APP/two_factor.py.
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',  # backup-коды на случай потери телефона
    # SSO через django-allauth (real OAuth: Google/Microsoft/GitHub).
    # Mock-SSO (Dolg_APP/sso_views.py) оставлен для demo Enterprise tier.
    # allauth требует django.contrib.sites — см. ниже SITE_ID.
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    *(
        []
        if SKIP_SOCIALACCOUNT_PROVIDERS
        else [
            'allauth.socialaccount.providers.google',
            'allauth.socialaccount.providers.microsoft',
            'allauth.socialaccount.providers.github',
        ]
    ),
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# Observability: django-prometheus отдаёт /metrics/ для Prometheus-scraper'а.
# Если пакет не установлен — пропускаем регистрацию (сервер не падает).
# Grafana stack подцепляется через docker-compose в deploy/.
try:
    if SKIP_OPTIONAL_APP_PROBES:
        raise ImportError
    import django_prometheus  # noqa: F401

    INSTALLED_APPS.append('django_prometheus')
    _HAS_PROMETHEUS = True
except ImportError:
    _HAS_PROMETHEUS = False

# Токен для машинного доступа к /metrics/ (Prometheus-скрейпер шлёт его в
# заголовке Authorization: Bearer <token> или ?token=). Пусто → доступ к
# метрикам только у staff-пользователей (fail-closed). См. Dolg_APP/metrics_guard.
METRICS_TOKEN = os.environ.get('METRICS_TOKEN', '')

# Optional security/dev libs — conditional import + STRICT opt-in.
# ВНИМАНИЕ: каждая из этих либ требует MIGRATIONS (axes, silk имеют свои таблицы).
# Если включить без миграций → ЛЮБОЙ view ломается → blank page.
# Default ВСЕГДА False; включается явно через env-var ПОСЛЕ `manage.py migrate`.
try:
    if SKIP_OPTIONAL_APP_PROBES:
        raise ImportError
    import axes  # noqa: F401

    _HAS_AXES = env_bool('ENABLE_AXES', False)
    if _HAS_AXES:
        INSTALLED_APPS.append('axes')
except ImportError:
    _HAS_AXES = False

try:
    if SKIP_OPTIONAL_APP_PROBES:
        raise ImportError
    import csp  # noqa: F401

    _HAS_CSP = env_bool('ENABLE_CSP', False)
except ImportError:
    _HAS_CSP = False

try:
    if SKIP_OPTIONAL_APP_PROBES:
        raise ImportError
    import silk  # noqa: F401

    _HAS_SILK = env_bool('ENABLE_SILK', False)
    if _HAS_SILK:
        INSTALLED_APPS.append('silk')
except ImportError:
    _HAS_SILK = False

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Fast liveness/readiness path before URLConf imports heavy app routes.
    'Dolg_APP.middleware.HealthzMiddleware',
    # 2026-06-01 v22: WhiteNoise — статика напрямую из приложения (Render не
    # запускает nginx). Должен быть СРАЗУ после SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # AnonymizeIPMiddleware — ДО SessionMiddleware: затирает REMOTE_ADDR
    # до того, как любой downstream-код успеет залогировать оригинал.
    'Dolg_APP.middleware.AnonymizeIPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # AnonSessionExpiryMiddleware — ПОСЛЕ AuthenticationMiddleware: нужен
    # request.user.is_authenticated. Сокращает TTL session-cookie до 24ч
    # для guest, авторизованные — стандартный SESSION_COOKIE_AGE.
    'Dolg_APP.middleware.AnonSessionExpiryMiddleware',
    # OTPMiddleware — django-otp. Сразу после Authentication: дополняет
    # request.user атрибутом is_verified() (True если этот session прошёл
    # 2FA challenge). Сам ничего не блокирует — enforcement в Require2FAMiddleware.
    'django_otp.middleware.OTPMiddleware',
    # Require2FAMiddleware — если user.is_authenticated И у него есть TOTPDevice,
    # И session не is_verified() → редирект на /2fa/verify/. Без этого можно
    # обойти 2FA, просто залогинившись по password.
    'Dolg_APP.middleware.Require2FAMiddleware',
    # AuditContextMiddleware — прокидывает request в thread-local чтобы
    # AuditLog.log мог достать IP/UA из произвольной точки кода (signals,
    # save-handlers). Ставим в конец цепочки.
    'Dolg_APP.middleware.AuditContextMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # allauth account middleware: дополняет session, проверяет rate-limit
    # на password attempts и т.п. Не критично, но требуется allauth >= 0.56.
    'allauth.account.middleware.AccountMiddleware',
]

# Prometheus middleware: добавляем ТОЛЬКО если пакет установлен (см. выше).
# Before — первым (засекает start_time), After — последним (status_code).
if _HAS_PROMETHEUS:
    MIDDLEWARE.insert(0, 'django_prometheus.middleware.PrometheusBeforeMiddleware')
    MIDDLEWARE.append('django_prometheus.middleware.PrometheusAfterMiddleware')

# Axes: brute-force защита /login/. Middleware и AUTH_BACKEND нужны вместе.
if _HAS_AXES:
    MIDDLEWARE.append('axes.middleware.AxesMiddleware')
    AUTHENTICATION_BACKENDS = ['axes.backends.AxesStandaloneBackend'] + globals().get(
        'AUTHENTICATION_BACKENDS', ['django.contrib.auth.backends.ModelBackend']
    )
    # Config: 5 failures за 15 минут → lock на 1 час
    AXES_FAILURE_LIMIT = 5
    AXES_COOLOFF_TIME = 1  # часов
    AXES_RESET_ON_SUCCESS = True

# CSP (Content Security Policy): защита от XSS. В DEBUG отключен (мешает hot-reload).
if _HAS_CSP:
    MIDDLEWARE.insert(1, 'csp.middleware.CSPMiddleware')  # после SecurityMiddleware
    # django-csp 4.0 читает ЕДИНЫЙ словарь CONTENT_SECURITY_POLICY; старый
    # формат CSP_* (django-csp <4) в 4.0 ИГНОРИРУЕТСЯ. Значения директив —
    # списки строк ("'self'" и т.п.).
    # 'unsafe-inline' пока ОСТАЁТСЯ — simulation.html содержит 15k+ строк
    # инлайн-JS; миграция на nonce — отдельная post-defense задача
    # [[project-security-backlog]] § 1.3. ВАЖНО: nonce и 'unsafe-inline'
    # взаимоисключающи (при наличии nonce браузер игнорит unsafe-inline и
    # рубит инлайн без nonce), поэтому пока nonce НЕ включаем.
    CONTENT_SECURITY_POLICY = {
        'DIRECTIVES': {
            'default-src': ["'self'"],
            'script-src': ["'self'", "'unsafe-inline'", 'cdn.jsdelivr.net', 'unpkg.com'],
            'style-src': ["'self'", "'unsafe-inline'", 'fonts.googleapis.com', 'cdn.jsdelivr.net'],
            'font-src': ["'self'", 'fonts.gstatic.com'],
            'img-src': ["'self'", 'data:', 'huggingface.co'],
            'connect-src': ["'self'", 'api.anthropic.com', 'huggingface.co'],
            'frame-ancestors': ["'none'"],  # защита от clickjacking
        },
    }

# Silk (профайлер) — opt-in, тяжёлый, только для dev/staging диагностики.
if _HAS_SILK:
    MIDDLEWARE.insert(1, 'silk.middleware.SilkyMiddleware')
    SILKY_PYTHON_PROFILER = False  # cprofile heavy — выключен
    SILKY_AUTHENTICATION = True
    SILKY_AUTHORISATION = True

    def _silk_admin_only(user):
        return user.is_authenticated and user.is_staff

    SILKY_PERMISSIONS = _silk_admin_only

ROOT_URLCONF = 'Dolg_PR.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.cart_count',
                'shop.context_processors.compare_list',
            ],
        },
    },
]

WSGI_APPLICATION = 'Dolg_PR.wsgi.application'

# ASGI / Channels — для WebSocket realtime-чата.
# Daphne (см. INSTALLED_APPS) подхватывает ASGI_APPLICATION и обслуживает
# /ws/ маршруты через Dolg_APP/routing.py.
ASGI_APPLICATION = 'Dolg_PR.asgi.application'

# Redis — общий инфраструктурный слой для production: Channels groups,
# Celery broker/result backend и будущие distributed locks. В dev/test без
# REDIS_URL оставляем in-memory fallback, чтобы локальный старт был простым.
REDIS_URL = os.getenv('REDIS_URL', '').strip()

# CHANNEL_LAYERS — транспорт для group_send/group_add. InMemory корректен
# только для одного процесса; при нескольких web/asgi replicas обязательно
# задавайте REDIS_URL=redis://redis:6379/0.
if REDIS_URL and not IS_TESTING:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [REDIS_URL]},
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

# Celery — foundation для async ML/import/PDF/batch-sim jobs. Конкретные
# долгие задачи мигрируются постепенно; worker уже можно поднимать в Docker.
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', REDIS_URL or 'memory://')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', REDIS_URL or 'cache+memory://')
CELERY_TASK_ALWAYS_EAGER = env_bool('CELERY_TASK_ALWAYS_EAGER', IS_TESTING)
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = 'Europe/Moscow'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


# DATABASE_URL — стандарт 12-factor. Если задан, парсим вручную (без
# зависимости dj-database-url) и переключаемся на Postgres. Иначе — SQLite.
# Поддерживаем postgresql:// и postgres:// (исторический алиас).
# В тестах (IS_TESTING) принудительно SQLite — быстрее и без внешней зависимости.
def _parse_database_url(url):
    """Минимальный парсер: postgresql://user:pwd@host:port/dbname?sslmode=require&...

    Query-параметры (?sslmode, ?connect_timeout и т.п.) пробрасываются в
    OPTIONS — managed Postgres (AWS RDS / Heroku / Yandex Managed) обычно
    требует TLS, и без sslmode=require коннект отвалится.
    """
    from urllib.parse import parse_qs, unquote, urlparse

    p = urlparse(url)
    options = {}
    for key, values in parse_qs(p.query).items():
        if values:
            options[key] = values[0]
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': (p.path or '').lstrip('/'),
        'USER': unquote(p.username or ''),
        'PASSWORD': unquote(p.password or ''),
        'HOST': p.hostname or '',
        'PORT': str(p.port or ''),
        'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),  # пул на 60 с
        'OPTIONS': options,
    }


_db_url = os.getenv('DATABASE_URL', '').strip()
if _db_url and not IS_TESTING and _db_url.split(':', 1)[0] in {'postgresql', 'postgres'}:
    DATABASES = {'default': _parse_database_url(_db_url)}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            # Без этих OPTIONS SQLite под Daphne/Channels (async, конкурентные
            # запросы браузера) ловит «database is locked» и ВИСНЕТ: один писатель
            # блокирует всех читателей → после «тяжёлой» страницы (каталог +
            # context-processors cart/compare на каждой странице) сервер жив, но
            # не отвечает ни на одну страницу. Лечится так:
            #   WAL          — читатели не блокируют писателя и наоборот;
            #   busy timeout — писатель ЖДЁТ блокировку (до 20с), а не падает сразу;
            #   IMMEDIATE    — меньше дедлоков на параллельных транзакциях (Django 5.1+).
            'OPTIONS': {
                'timeout': 20,
                'transaction_mode': 'IMMEDIATE',
                'init_command': (
                    'PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL; PRAGMA foreign_keys=ON;'
                ),
            },
        }
    }

# Opt-in быстрые тесты: при FAST_TESTS=1 Django пропускает прогон миграций
# и создаёт схему напрямую из моделей (создаст ровно те таблицы, что нужны).
# Снижает время прогона Dolg_APP с ~12 минут до ~2-3 (миграции — главный
# вкладчик). Поведение по умолчанию НЕ меняется — миграции прогоняются
# (нужно для тестов, которые проверяют миграционную семантику).
# Использование:  $env:FAST_TESTS=1; manage.py test
if IS_TESTING and env_bool('FAST_TESTS'):

    class _DisableMigrations:
        def __contains__(self, _item):
            return True

        def __getitem__(self, _item):
            return None

    MIGRATION_MODULES = _DisableMigrations()


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# В тестах форсируем MD5-хешер: bcrypt по умолчанию делает 12 раундов
# (~250 мс на хеш), и сюита с десятками User.objects.create_user в setUp'ах
# тратит дополнительно 5-10 секунд на тест. MD5 даёт ~0.1 мс — порядок
# ускорения. БЕЗОПАСНО для тестов (никакие реальные пароли не хешатся).
# Включается только при IS_TESTING — production не затронут.
if IS_TESTING:
    PASSWORD_HASHERS = [
        'django.contrib.auth.hashers.MD5PasswordHasher',
    ]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Для защиты и локального запуска с DEBUG=False: если collectstatic еще не
# прогнали, один отсутствующий manifest-entry не должен валить всю страницу.
# В production collectstatic все равно обязателен для нормального кеширования.
WHITENOISE_MANIFEST_STRICT = False
# 2026-06-01 v22: WhiteNoise storage с compression. Hash-manifest включается
# только явным env-флагом: иначе локальный DEBUG=False без collectstatic валит
# страницы на Missing staticfiles manifest entry.
USE_MANIFEST_STATIC = env_bool('USE_MANIFEST_STATIC', False)
if not DEBUG and not IS_TESTING:
    static_backend = (
        'whitenoise.storage.CompressedManifestStaticFilesStorage'
        if USE_MANIFEST_STATIC
        else 'whitenoise.storage.CompressedStaticFilesStorage'
    )
    STORAGES = {
        'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
        'staticfiles': {'BACKEND': static_backend},
    }

# В production — ManifestStaticFilesStorage добавляет hash в имя файла
# (pixi.abc123.js), что снимает ручной кэш-бастинг через ?v=20260506a в
# шаблонах и позволяет CDN кешировать статику без ограничений.
# Включается только при DEBUG=False — при разработке хеши усложняют отладку.
# Для тестов и dev-сервера остаётся стандартный StaticFilesStorage.

# Media files (uploaded images)
# https://docs.djangoproject.com/en/4.2/topics/files/

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Local diploma/demo mode needs Django to serve uploaded/generated media even
# when DEBUG is disabled. Production with nginx can set SERVE_MEDIA=0.
SERVE_MEDIA = env_bool('SERVE_MEDIA', True)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AI-ассистент (Claude API). Без ключа endpoint работает в demo-режиме —
# UI отдаёт пользователю понятное сообщение «AI временно недоступен» и не
# падает. Боевое значение задаётся через переменную окружения.
# (Состояние «включён/нет» спрашиваем через ai_assistant.is_enabled() —
# отдельной переменной не держим, чтобы не было двух источников истины.)
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY', '')

# Sentry — opt-in через переменную окружения SENTRY_DSN. Если она задана и
# sentry_sdk установлен (`pip install sentry-sdk`), инициализируется в
# production-mode (DEBUG=False). Sample rate настраивается отдельно.
# Без переменной — никаких внешних соединений и зависимостей.
SENTRY_DSN = os.getenv('SENTRY_DSN', '')
SENTRY_TRACES_SAMPLE_RATE = float(os.getenv('SENTRY_TRACES_SAMPLE_RATE', '0.0'))
SENTRY_ENVIRONMENT = os.getenv('SENTRY_ENVIRONMENT', 'production' if not DEBUG else 'development')

if SENTRY_DSN and not IS_TESTING:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration

        # release-tagging: связать ошибки с конкретным деплоем. CI/CD должен
        # передать SHA коммита через RELEASE_SHA. Без него — fallback на
        # дату/час, чтобы хотя бы группировка по деплоям работала.
        release = os.getenv('RELEASE_SHA') or os.getenv('GIT_SHA')
        if not release:
            import datetime

            release = 'dolg@' + datetime.datetime.utcnow().strftime('%Y%m%d-%H')
        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            traces_sample_rate=SENTRY_TRACES_SAMPLE_RATE,
            send_default_pii=False,  # PII off — у нас email/username не нужны Sentry-у
            environment=SENTRY_ENVIRONMENT,
            release=release,
        )
    except ImportError:
        warnings.warn(
            'SENTRY_DSN задан, но пакет sentry-sdk не установлен. Поставьте: pip install sentry-sdk',
            RuntimeWarning,
        )

# Ops-алерты (ошибки/безопасность) в отдельный канал — НЕ в чат. См. Dolg_APP/services/ops_alerts.py
# Канал выбирается одной env-переменной (webhook авто-формат Slack/Discord/Telegram), иначе email ADMINS.
OPS_ALERT_WEBHOOK_URL = os.getenv('OPS_ALERT_WEBHOOK_URL', '')
OPS_ALERT_TELEGRAM_CHAT_ID = os.getenv('OPS_ALERT_TELEGRAM_CHAT_ID', '')
OPS_ALERT_MIN_LEVEL = os.getenv('OPS_ALERT_MIN_LEVEL', 'warning')
OPS_ALERT_THROTTLE_SEC = int(os.getenv('OPS_ALERT_THROTTLE_SEC', '300'))

# ADMINS для email-фолбэка ops-алертов. Формат env: "Имя <a@b.c>, Имя2 <d@e.f>".
_ops_admins = os.getenv('DJANGO_ADMINS', '')
if _ops_admins:
    ADMINS = [
        (p.split('<')[0].strip() or 'admin', p.split('<')[1].rstrip('>').strip())
        for p in _ops_admins.split(',')
        if '<' in p
    ]
    SERVER_EMAIL = os.getenv('SERVER_EMAIL', DEFAULT_FROM_EMAIL)

# Stripe Payment Configuration
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY', 'demo_mode')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', 'demo_mode')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', 'demo_mode')

# Stripe Price ID для Pro-подписки. Создаётся вручную в Stripe Dashboard
# (Products → Pro plan → Pricing → recurring monthly), price_id вида
# price_xxxxx копируется сюда через env. В demo-mode не используется.
STRIPE_PRO_PRICE_ID = os.getenv('STRIPE_PRO_PRICE_ID', '')

# === 2FA через django-otp ===
# OTP_TOTP_ISSUER — отображается в Authenticator-приложении («DOLG: alice@…»).
# Не зависит от localization — английский OK даже для русских пользователей.
OTP_TOTP_ISSUER = 'DOLG'
# При rerun сервера TOTP-токены не должны инвалидироваться. django-otp
# уже не привязывает их к процессу, но явно зафиксируем секрет для шифрования
# raw-секретов в БД (Fernet под капотом).
OTP_TOTP_THROTTLE_FACTOR = 1  # без throttle — для дипломной демки

# === SSO через django-allauth ===
# SITE_ID — обязательно для django.contrib.sites (используется allauth для
# callback-URL). На локальной разработке создаётся автоматически при migrate.
SITE_ID = 1

# Backends авторизации: стандартный + allauth.
# Порядок имеет значение — first wins.
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # email/password
    'allauth.account.auth_backends.AuthenticationBackend',  # SSO
]

# allauth конфиг: используем email как primary identifier (без username при SSO).
ACCOUNT_LOGIN_METHODS = {'email', 'username'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # для demo; на проде — 'mandatory'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/5m',  # 5 неудачных попыток за 5 мин → throttle
}

# Social account настройки. Provider'ы конфигурируются через
# /admin/socialaccount/socialapp/ ИЛИ через SOCIALACCOUNT_PROVIDERS env.
# По умолчанию в demo-mode ничего не сконфигурировано — кнопки SSO неактивны.
SOCIALACCOUNT_LOGIN_ON_GET = True  # один клик «Войти через Google» вместо confirm-страницы
SOCIALACCOUNT_AUTO_SIGNUP = True  # создаёт User автоматически при первом SSO-входе
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'  # email от Google УЖЕ verified
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        # Credentials в /admin/socialaccount/socialapp/ — НЕ в settings.py
        # (чтобы не хранить secrets в коде).
    },
    'microsoft': {
        'TENANT': 'common',  # all Azure AD tenants + personal accounts
    },
    'github': {
        'SCOPE': ['read:user', 'user:email'],
    },
}

# После SSO-логина возвращаем на профиль (или ?next=...)
LOGIN_REDIRECT_URL = '/accounts/profile/'
LOGOUT_REDIRECT_URL = '/'

# Payment Settings
PAYMENT_CURRENCY = 'RUB'
PAYMENT_BACKEND = 'stripe'

# Security settings (active in production when DEBUG=False)
SESSION_COOKIE_HTTPONLY = True
# CSRF-cookie должен быть читаемым из JS — симулятор и CAD отправляют fetch-запросы
# к API (BOM, projects, save/load) и берут токен через document.cookie.
# CSRF-защита сохраняется: атакующий не может прочитать cookie с чужого origin.
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SECURE = (not DEBUG) and (not IS_TESTING)
CSRF_COOKIE_SECURE = (not DEBUG) and (not IS_TESTING)
SECURE_SSL_REDIRECT = (not DEBUG) and (not IS_TESTING)
SECURE_HSTS_SECONDS = 31536000 if (not DEBUG and not IS_TESTING) else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = (not DEBUG) and (not IS_TESTING)
SECURE_HSTS_PRELOAD = (not DEBUG) and (not IS_TESTING)
# defense-in-depth: даже если будущий MIME-sniff trick найдут, браузер не
# попытается «угадать» content-type ответа.
SECURE_CONTENT_TYPE_NOSNIFF = True
# Referrer-Policy: не утекаем path/query на внешние сайты при клике по ссылке.
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
# Cross-Origin-Opener-Policy: изоляция window-объекта от других origin.
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'

# SameSite=Lax — баланс между UX (внешние ссылки на shop работают) и
# защитой от CSRF (cross-site POST не отправляет cookies).
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# --- Reverse-proxy / туннели (Cloudflare, ngrok, nginx, gunicorn) ----------
# Cloudflare Tunnel — главный кейс: пользователь видит https://random.trycloudflare.com,
# а до Django запрос приходит как обычный HTTP на localhost:8000. Cloudflare
# проставляет заголовок X-Forwarded-Proto: https. Без этой настройки:
#   • request.is_secure() = False → Cookie Secure не работают (login не сохраняется)
#   • build_absolute_uri() выдаёт http://... ссылки (verify-email, share-link)
#   • в проде SECURE_SSL_REDIRECT даст infinite-redirect-loop
# Включаем по умолчанию — никакого вреда в DEV (там этот header просто отсутствует).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# request.get_host() возвращает внешний хост (.trycloudflare.com), а не
# localhost из Host-заголовка. Cloudflare пробрасывает X-Forwarded-Host.
USE_X_FORWARDED_HOST = True

# Logging: console-handler со скрабингом чувствительных данных (PII/секреты).
# disable_existing_loggers=False — не глушим Django-логгеры, только добавляем
# фильтр маскировки ключей/токенов/паролей/email (см. Dolg_APP/log_scrub).
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'scrub_sensitive': {'()': 'Dolg_APP.log_scrub.SensitiveDataFilter'},
    },
    'formatters': {
        'standard': {'format': '%(levelname)s %(asctime)s %(name)s %(message)s'},
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'filters': ['scrub_sensitive'],
            'formatter': 'standard',
        },
    },
    'root': {'handlers': ['console'], 'level': os.environ.get('LOG_LEVEL', 'INFO')},
}

# Ops-алерты через logging: handler пробрасывает WARNING+ в notify_ops (отдельный канал).
if not IS_TESTING:
    LOGGING['handlers']['ops_alert'] = {
        'class': 'Dolg_APP.services.ops_alerts.OpsAlertLogHandler',
        'level': 'WARNING',
        'filters': ['scrub_sensitive'],
    }
    # Логгер событий безопасности: код шлёт logging.getLogger('dolg.security').warning(...).
    LOGGING.setdefault('loggers', {})['dolg.security'] = {
        'handlers': ['console', 'ops_alert'],
        'level': 'WARNING',
        'propagate': False,
    }
    # 500-е ошибки в ops-канал — только если канал реально настроен (иначе дубль в консоль в dev).
    if OPS_ALERT_WEBHOOK_URL or globals().get('ADMINS'):
        LOGGING['loggers']['django.request'] = {
            'handlers': ['console', 'ops_alert'],
            'level': 'ERROR',
            'propagate': False,
        }
