"""
Django settings for ROMAN_PR project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
import warnings
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Подгружаем .env из корня проекта ДО любого os.getenv() — иначе HF_TOKEN,
# ANTHROPIC_API_KEY, SECRET_KEY и прочие переменные не подхватятся.
# .env уже в .gitignore — секреты не попадут в репозиторий.
# Если python-dotenv не установлен — пропускаем, переменные нужно задавать руками.
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env', override=False)
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on', 'dev', 'debug'}


def env_list(name, default):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(',') if item.strip()]


IS_TESTING = 'test' in sys.argv or 'pytest' in sys.argv[0].lower() or any('pytest' in a for a in sys.argv)

DEFAULT_INSECURE_SECRET_KEY = 'django-insecure-local-development-key-change-me'
SECRET_KEY = os.getenv('SECRET_KEY', DEFAULT_INSECURE_SECRET_KEY)

DEBUG = env_bool('DEBUG', True)

ALLOWED_HOSTS = env_list(
    'ALLOWED_HOSTS',
    # .localhost — wildcard для всех субдоменов localhost (dolg.localhost, shop.localhost и т.п.)
    # Современные браузеры резолвят *.localhost в 127.0.0.1 без hosts-файла (RFC 6761).
    # .local оставлен как опциональный fallback (требует правки hosts).
    # .trycloudflare.com — домены Cloudflare Quick Tunnel (для демо публичного доступа).
    # .ngrok-free.app / .ngrok.io — ngrok (на случай переключения туннеля).
    'localhost,127.0.0.1,[::1],.localhost,dolg.local,shop.dolg.local,www.dolg.local,'
    '.trycloudflare.com,.ngrok-free.app,.ngrok.io'
)

# CSRF trusted origins — Django 4.0+ требует явно перечислить источники
# для POST-запросов с https/non-default домена.
CSRF_TRUSTED_ORIGINS = env_list(
    'CSRF_TRUSTED_ORIGINS',
    'https://*.trycloudflare.com,https://*.ngrok-free.app,https://*.ngrok.io'
)

if not DEBUG and SECRET_KEY == DEFAULT_INSECURE_SECRET_KEY and not IS_TESTING:
    warnings.warn(
        'SECRET_KEY is not set while DEBUG is disabled. Use .env.example as a template '
        'and set a unique SECRET_KEY before production/demo deployment.',
        RuntimeWarning,
    )

if not DEBUG and not ALLOWED_HOSTS and not IS_TESTING:
    warnings.warn(
        'ALLOWED_HOSTS is empty while DEBUG is disabled. Set ALLOWED_HOSTS before deployment.',
        RuntimeWarning,
    )

EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend',
)
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'DOLG <noreply@dolg.local>')


# Application definition

INSTALLED_APPS = [
    # daphne ДО django.contrib.staticfiles — Django requirement для ASGI.
    # daphne подменяет runserver на ASGI-сервер, что даёт WebSocket-поддержку
    # в dev-режиме без отдельного процесса. В production — отдельный daphne/uvicorn.
    'daphne',
    'Dolg_APP',
    'shop',
    'accounts',
    'orders',
    'knowledge',
    'moderation',
    'channels',
    # 2FA через django-otp: TOTPDevice (Google Authenticator / Authy / 1Password).
    # Enforcement по org-policy require_2fa — см. Dolg_APP/two_factor.py.
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',   # backup-коды на случай потери телефона
    # SSO через django-allauth (real OAuth: Google/Microsoft/GitHub).
    # Mock-SSO (Dolg_APP/sso_views.py) оставлен для demo Enterprise tier.
    # allauth требует django.contrib.sites — см. ниже SITE_ID.
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.microsoft',
    'allauth.socialaccount.providers.github',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# Observability: django-prometheus отдаёт /metrics/ для Prometheus-scraper'а.
# Если пакет не установлен — пропускаем регистрацию (сервер не падает).
# Grafana stack подцепляется через docker-compose в deploy/.
try:
    import django_prometheus  # noqa: F401
    INSTALLED_APPS.append('django_prometheus')
    _HAS_PROMETHEUS = True
except ImportError:
    _HAS_PROMETHEUS = False

# Optional security/dev libs — conditional import + STRICT opt-in.
# ВНИМАНИЕ: каждая из этих либ требует MIGRATIONS (axes, silk имеют свои таблицы).
# Если включить без миграций → ЛЮБОЙ view ломается → blank page.
# Default ВСЕГДА False; включается явно через env-var ПОСЛЕ `manage.py migrate`.
try:
    import axes  # noqa: F401
    _HAS_AXES = env_bool('ENABLE_AXES', False)
    if _HAS_AXES:
        INSTALLED_APPS.append('axes')
except ImportError:
    _HAS_AXES = False

try:
    import csp  # noqa: F401
    _HAS_CSP = env_bool('ENABLE_CSP', False)
except ImportError:
    _HAS_CSP = False

try:
    import silk  # noqa: F401
    _HAS_SILK = env_bool('ENABLE_SILK', False)
    if _HAS_SILK:
        INSTALLED_APPS.append('silk')
except ImportError:
    _HAS_SILK = False

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # AnonymizeIPMiddleware — ДО SessionMiddleware: затирает REMOTE_ADDR
    # до того, как любой downstream-код успеет залогировать оригинал.
    'Dolg_APP.middleware.AnonymizeIPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # AnonSessionExpiryMiddleware — ПОСЛЕ AuthenticationMiddleware: нужен
    # request.user.is_authenticated. Сокращает TTL session-cookie до 24ч
    # для guest, авторизованные — стандартный SESSION_COOKIE_AGE.
    'Dolg_APP.middleware.AnonSessionExpiryMiddleware',
    # OTPMiddleware — django-otp. Сразу после Authentication: дополняет
    # request.user атрибутом is_verified() (True если этот session прошёл
    # 2FA challenge). Сам ничего не блокирует — enforcement в Require2FAMiddleware.
    'django_otp.middleware.OTPMiddleware',
    # Require2FAMiddleware — если user.is_authenticated И у него есть TOTPDevice,
    # И session не is_verified() → редирект на /2fa/verify/. Без этого можно
    # обойти 2FA, просто залогинившись по password.
    'Dolg_APP.middleware.Require2FAMiddleware',
    # AuditContextMiddleware — прокидывает request в thread-local чтобы
    # AuditLog.log мог достать IP/UA из произвольной точки кода (signals,
    # save-handlers). Ставим в конец цепочки.
    'Dolg_APP.middleware.AuditContextMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # allauth account middleware: дополняет session, проверяет rate-limit
    # на password attempts и т.п. Не критично, но требуется allauth >= 0.56.
    'allauth.account.middleware.AccountMiddleware',
]

# Prometheus middleware: добавляем ТОЛЬКО если пакет установлен (см. выше).
# Before — первым (засекает start_time), After — последним (status_code).
if _HAS_PROMETHEUS:
    MIDDLEWARE.insert(0, 'django_prometheus.middleware.PrometheusBeforeMiddleware')
    MIDDLEWARE.append('django_prometheus.middleware.PrometheusAfterMiddleware')

# Axes: brute-force защита /login/. Middleware и AUTH_BACKEND нужны вместе.
if _HAS_AXES:
    MIDDLEWARE.append('axes.middleware.AxesMiddleware')
    AUTHENTICATION_BACKENDS = ['axes.backends.AxesStandaloneBackend'] + globals().get(
        'AUTHENTICATION_BACKENDS', ['django.contrib.auth.backends.ModelBackend']
    )
    # Config: 5 failures за 15 минут → lock на 1 час
    AXES_FAILURE_LIMIT = 5
    AXES_COOLOFF_TIME = 1  # часов
    AXES_RESET_ON_SUCCESS = True

# CSP (Content Security Policy): защита от XSS. В DEBUG отключен (мешает hot-reload).
if _HAS_CSP:
    MIDDLEWARE.insert(1, 'csp.middleware.CSPMiddleware')  # после SecurityMiddleware
    # Базовый профиль — self только, + CDN для нескольких внешних либ
    CSP_DEFAULT_SRC = ("'self'",)
    CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", 'cdn.jsdelivr.net', 'unpkg.com')
    CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", 'fonts.googleapis.com', 'cdn.jsdelivr.net')
    CSP_FONT_SRC = ("'self'", 'fonts.gstatic.com')
    CSP_IMG_SRC = ("'self'", 'data:', 'huggingface.co')
    CSP_CONNECT_SRC = ("'self'", 'api.anthropic.com', 'huggingface.co')
    CSP_FRAME_ANCESTORS = ("'none'",)  # защита от clickjacking

# Silk (профайлер) — opt-in, тяжёлый, только для dev/staging диагностики.
if _HAS_SILK:
    MIDDLEWARE.insert(1, 'silk.middleware.SilkyMiddleware')
    SILKY_PYTHON_PROFILER = False  # cprofile heavy — выключен
    SILKY_AUTHENTICATION = True
    SILKY_AUTHORISATION = True
    def _silk_admin_only(user):
        return user.is_authenticated and user.is_staff
    SILKY_PERMISSIONS = _silk_admin_only

ROOT_URLCONF = 'Dolg_PR.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.cart_count',
                'shop.context_processors.compare_list',
            ],
        },
    },
]

WSGI_APPLICATION = 'Dolg_PR.wsgi.application'

# ASGI / Channels — для WebSocket realtime-чата.
# Daphne (см. INSTALLED_APPS) подхватывает ASGI_APPLICATION и обслуживает
# /ws/ маршруты через Dolg_APP/routing.py.
ASGI_APPLICATION = 'Dolg_PR.asgi.application'

# CHANNEL_LAYERS — транспорт для group_send/group_add. На dev и для дипломной
# нагрузки достаточно in-memory (один процесс, всё в одной памяти). В prod
# понадобится channels-redis (`pip install channels-redis`), тогда:
#   CHANNEL_LAYERS = {'default': {'BACKEND': 'channels_redis.core.RedisChannelLayer',
#                                  'CONFIG': {'hosts': [('redis', 6379)]}}}
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASE_URL — стандарт 12-factor. Если задан, парсим вручную (без
# зависимости dj-database-url) и переключаемся на Postgres. Иначе — SQLite.
# Поддерживаем postgresql:// и postgres:// (исторический алиас).
# В тестах (IS_TESTING) принудительно SQLite — быстрее и без внешней зависимости.
def _parse_database_url(url):
    """Минимальный парсер: postgresql://user:pwd@host:port/dbname?sslmode=require&...

    Query-параметры (?sslmode, ?connect_timeout и т.п.) пробрасываются в
    OPTIONS — managed Postgres (AWS RDS / Heroku / Yandex Managed) обычно
    требует TLS, и без sslmode=require коннект отвалится.
    """
    from urllib.parse import parse_qs, unquote, urlparse
    p = urlparse(url)
    options = {}
    for key, values in parse_qs(p.query).items():
        if values:
            options[key] = values[0]
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME':   (p.path or '').lstrip('/'),
        'USER':   unquote(p.username or ''),
        'PASSWORD': unquote(p.password or ''),
        'HOST':   p.hostname or '',
        'PORT':   str(p.port or ''),
        'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),  # пул на 60 с
        'OPTIONS': options,
    }


_db_url = os.getenv('DATABASE_URL', '').strip()
if _db_url and not IS_TESTING and _db_url.split(':', 1)[0] in {'postgresql', 'postgres'}:
    DATABASES = {'default': _parse_database_url(_db_url)}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Opt-in быстрые тесты: при FAST_TESTS=1 Django пропускает прогон миграций
# и создаёт схему напрямую из моделей (создаст ровно те таблицы, что нужны).
# Снижает время прогона Dolg_APP с ~12 минут до ~2-3 (миграции — главный
# вкладчик). Поведение по умолчанию НЕ меняется — миграции прогоняются
# (нужно для тестов, которые проверяют миграционную семантику).
# Использование:  $env:FAST_TESTS=1; manage.py test
if IS_TESTING and env_bool('FAST_TESTS'):
    class _DisableMigrations:
        def __contains__(self, _item): return True
        def __getitem__(self, _item): return None
    MIGRATION_MODULES = _DisableMigrations()


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# В тестах форсируем MD5-хешер: bcrypt по умолчанию делает 12 раундов
# (~250 мс на хеш), и сюита с десятками User.objects.create_user в setUp'ах
# тратит дополнительно 5-10 секунд на тест. MD5 даёт ~0.1 мс — порядок
# ускорения. БЕЗОПАСНО для тестов (никакие реальные пароли не хешатся).
# Включается только при IS_TESTING — production не затронут.
if IS_TESTING:
    PASSWORD_HASHERS = [
        'django.contrib.auth.hashers.MD5PasswordHasher',
    ]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# В production — ManifestStaticFilesStorage добавляет hash в имя файла
# (pixi.abc123.js), что снимает ручной кэш-бастинг через ?v=20260506a в
# шаблонах и позволяет CDN кешировать статику без ограничений.
# Включается только при DEBUG=False — при разработке хеши усложняют отладку.
# Для тестов и dev-сервера остаётся стандартный StaticFilesStorage.
USE_MANIFEST_STATIC = env_bool('USE_MANIFEST_STATIC', False)
if not DEBUG and not IS_TESTING and USE_MANIFEST_STATIC:
    STORAGES = {
        'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage',
        },
    }

# Media files (uploaded images)
# https://docs.djangoproject.com/en/4.2/topics/files/

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Local diploma/demo mode needs Django to serve uploaded/generated media even
# when DEBUG is disabled. Production with nginx can set SERVE_MEDIA=0.
SERVE_MEDIA = env_bool('SERVE_MEDIA', True)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AI-ассистент (Claude API). Без ключа endpoint работает в demo-режиме —
# UI отдаёт пользователю понятное сообщение «AI временно недоступен» и не
# падает. Боевое значение задаётся через переменную окружения.
# (Состояние «включён/нет» спрашиваем через ai_assistant.is_enabled() —
# отдельной переменной не держим, чтобы не было двух источников истины.)
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY', '')

# Sentry — opt-in через переменную окружения SENTRY_DSN. Если она задана и
# sentry_sdk установлен (`pip install sentry-sdk`), инициализируется в
# production-mode (DEBUG=False). Sample rate настраивается отдельно.
# Без переменной — никаких внешних соединений и зависимостей.
SENTRY_DSN = os.getenv('SENTRY_DSN', '')
SENTRY_TRACES_SAMPLE_RATE = float(os.getenv('SENTRY_TRACES_SAMPLE_RATE', '0.0'))
SENTRY_ENVIRONMENT = os.getenv('SENTRY_ENVIRONMENT', 'production' if not DEBUG else 'development')

if SENTRY_DSN and not IS_TESTING:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        # release-tagging: связать ошибки с конкретным деплоем. CI/CD должен
        # передать SHA коммита через RELEASE_SHA. Без него — fallback на
        # дату/час, чтобы хотя бы группировка по деплоям работала.
        release = os.getenv('RELEASE_SHA') or os.getenv('GIT_SHA')
        if not release:
            import datetime
            release = 'dolg@' + datetime.datetime.utcnow().strftime('%Y%m%d-%H')
        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            traces_sample_rate=SENTRY_TRACES_SAMPLE_RATE,
            send_default_pii=False,  # PII off — у нас email/username не нужны Sentry-у
            environment=SENTRY_ENVIRONMENT,
            release=release,
        )
    except ImportError:
        warnings.warn(
            'SENTRY_DSN задан, но пакет sentry-sdk не установлен. '
            'Поставьте: pip install sentry-sdk',
            RuntimeWarning,
        )

# Stripe Payment Configuration
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY', 'demo_mode')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', 'demo_mode')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', 'demo_mode')

# Stripe Price ID для Pro-подписки. Создаётся вручную в Stripe Dashboard
# (Products → Pro plan → Pricing → recurring monthly), price_id вида
# price_xxxxx копируется сюда через env. В demo-mode не используется.
STRIPE_PRO_PRICE_ID = os.getenv('STRIPE_PRO_PRICE_ID', '')

# === 2FA через django-otp ===
# OTP_TOTP_ISSUER — отображается в Authenticator-приложении («DOLG: alice@…»).
# Не зависит от localization — английский OK даже для русских пользователей.
OTP_TOTP_ISSUER = 'DOLG'
# При rerun сервера TOTP-токены не должны инвалидироваться. django-otp
# уже не привязывает их к процессу, но явно зафиксируем секрет для шифрования
# raw-секретов в БД (Fernet под капотом).
OTP_TOTP_THROTTLE_FACTOR = 1   # без throttle — для дипломной демки

# === SSO через django-allauth ===
# SITE_ID — обязательно для django.contrib.sites (используется allauth для
# callback-URL). На локальной разработке создаётся автоматически при migrate.
SITE_ID = 1

# Backends авторизации: стандартный + allauth.
# Порядок имеет значение — first wins.
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',          # email/password
    'allauth.account.auth_backends.AuthenticationBackend', # SSO
]

# allauth конфиг: используем email как primary identifier (без username при SSO).
ACCOUNT_LOGIN_METHODS = {'email', 'username'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'optional'   # для demo; на проде — 'mandatory'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/5m',   # 5 неудачных попыток за 5 мин → throttle
}

# Social account настройки. Provider'ы конфигурируются через
# /admin/socialaccount/socialapp/ ИЛИ через SOCIALACCOUNT_PROVIDERS env.
# По умолчанию в demo-mode ничего не сконфигурировано — кнопки SSO неактивны.
SOCIALACCOUNT_LOGIN_ON_GET = True   # один клик «Войти через Google» вместо confirm-страницы
SOCIALACCOUNT_AUTO_SIGNUP = True    # создаёт User автоматически при первом SSO-входе
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'   # email от Google УЖЕ verified
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        # Credentials в /admin/socialaccount/socialapp/ — НЕ в settings.py
        # (чтобы не хранить secrets в коде).
    },
    'microsoft': {
        'TENANT': 'common',   # all Azure AD tenants + personal accounts
    },
    'github': {
        'SCOPE': ['read:user', 'user:email'],
    },
}

# После SSO-логина возвращаем на профиль (или ?next=...)
LOGIN_REDIRECT_URL = '/accounts/profile/'
LOGOUT_REDIRECT_URL = '/'

# Payment Settings
PAYMENT_CURRENCY = 'RUB'
PAYMENT_BACKEND = 'stripe'

# Security settings (active in production when DEBUG=False)
SESSION_COOKIE_HTTPONLY = True
# CSRF-cookie должен быть читаемым из JS — симулятор и CAD отправляют fetch-запросы
# к API (BOM, projects, save/load) и берут токен через document.cookie.
# CSRF-защита сохраняется: атакующий не может прочитать cookie с чужого origin.
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SECURE = (not DEBUG) and (not IS_TESTING)
CSRF_COOKIE_SECURE = (not DEBUG) and (not IS_TESTING)
SECURE_SSL_REDIRECT = (not DEBUG) and (not IS_TESTING)
SECURE_HSTS_SECONDS = 31536000 if (not DEBUG and not IS_TESTING) else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = (not DEBUG) and (not IS_TESTING)
SECURE_HSTS_PRELOAD = (not DEBUG) and (not IS_TESTING)
# defense-in-depth: даже если будущий MIME-sniff trick найдут, браузер не
# попытается «угадать» content-type ответа.
SECURE_CONTENT_TYPE_NOSNIFF = True
# Referrer-Policy: не утекаем path/query на внешние сайты при клике по ссылке.
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
# Cross-Origin-Opener-Policy: изоляция window-объекта от других origin.
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'

# SameSite=Lax — баланс между UX (внешние ссылки на shop работают) и
# защитой от CSRF (cross-site POST не отправляет cookies).
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# --- Reverse-proxy / туннели (Cloudflare, ngrok, nginx, gunicorn) ----------
# Cloudflare Tunnel — главный кейс: пользователь видит https://random.trycloudflare.com,
# а до Django запрос приходит как обычный HTTP на localhost:8000. Cloudflare
# проставляет заголовок X-Forwarded-Proto: https. Без этой настройки:
#   • request.is_secure() = False → Cookie Secure не работают (login не сохраняется)
#   • build_absolute_uri() выдаёт http://... ссылки (verify-email, share-link)
#   • в проде SECURE_SSL_REDIRECT даст infinite-redirect-loop
# Включаем по умолчанию — никакого вреда в DEV (там этот header просто отсутствует).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# request.get_host() возвращает внешний хост (.trycloudflare.com), а не
# localhost из Host-заголовка. Cloudflare пробрасывает X-Forwarded-Host.
USE_X_FORWARDED_HOST = True
