# Generated by Django 6.0.4 on 2026-04-24 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('topic', models.CharField(choices=[('physics', 'Физика и теория'), ('components', 'Компоненты'), ('packages', 'Корпуса и монтаж'), ('pcb', 'Печатные платы'), ('history', 'История электроники'), ('practice', 'Инженерная практика')], default='physics', max_length=20)),
                ('icon', models.CharField(default='📘', help_text='Emoji-иконка для карточки', max_length=8)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Категория знаний',
                'verbose_name_plural': 'Категории знаний',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('summary', models.TextField(help_text='Короткая аннотация для карточки (1–2 предложения)', max_length=400)),
                ('body', models.TextField(help_text='Основной текст. Поддерживает простую HTML-разметку (p, h3, ul, li, code, img).')),
                ('related_components_note', models.CharField(blank=True, help_text='Опциональная подсказка: какие категории товаров связаны.', max_length=200)),
                ('reading_minutes', models.PositiveSmallIntegerField(default=3)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='knowledge.knowledgecategory')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['category__order', 'order', 'title'],
            },
        ),
    ]
