# Generated by Django 6.0.4 on 2026-05-11 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('datasheet', 'Datasheet / PDF'), ('calculator', 'Калькулятор'), ('example', 'Пример схемы'), ('checklist', 'Чек-лист'), ('video', 'Видео'), ('external', 'Внешний материал'), ('file', 'Файл')], default='external', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='knowledge_materials/')),
                ('order', models.PositiveSmallIntegerField(default=100)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='knowledge.article')),
            ],
            options={
                'verbose_name': 'Материал статьи',
                'verbose_name_plural': 'Материалы статьи',
                'ordering': ['order', 'title'],
                'constraints': [models.UniqueConstraint(fields=('article', 'title'), name='unique_article_material_title')],
            },
        ),
    ]
