# Generated by Django 6.0.4 on 2026-05-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_articlematerial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlematerial',
            name='material_type',
            field=models.CharField(choices=[('datasheet', 'Datasheet / PDF'), ('calculator', 'Калькулятор'), ('example', 'Пример схемы'), ('checklist', 'Чек-лист'), ('image', 'Изображение'), ('animation', 'Анимация'), ('video', 'Видео'), ('external', 'Внешний материал'), ('file', 'Файл')], default='external', max_length=20),
        ),
        migrations.AlterField(
            model_name='articlematerial',
            name='url',
            field=models.CharField(blank=True, help_text='Внешняя ссылка или внутренний путь сайта, например /simulation/', max_length=300),
        ),
    ]
