# Generated by Django 6.0.4 on 2026-05-17 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dolg_APP', '0006_alter_schematicproject_options_and_more'),
        ('knowledge', '0003_alter_articlematerial_material_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('summary', models.TextField(max_length=500)),
                ('level', models.CharField(choices=[('basic', 'Начальный'), ('medium', 'Средний'), ('advanced', 'Продвинутый')], default='basic', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=100)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Учебный маршрут',
                'verbose_name_plural': 'Учебные маршруты',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LearningLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('summary', models.TextField(max_length=500)),
                ('theory', models.TextField(help_text='Теория урока. Поддерживает простую HTML-разметку.')),
                ('formula', models.CharField(blank=True, max_length=220)),
                ('action_url', models.CharField(blank=True, max_length=300)),
                ('action_label', models.CharField(blank=True, max_length=120)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=8)),
                ('order', models.PositiveSmallIntegerField(default=100)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_lessons', to='knowledge.article')),
                ('demo_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_lessons', to='Dolg_APP.schematicproject')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='knowledge.learningtrack')),
            ],
            options={
                'verbose_name': 'Учебный урок',
                'verbose_name_plural': 'Учебные уроки',
                'ordering': ['track__order', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LearningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('math_numeric', 'Математическая задача'), ('circuit_build', 'Сборка схемы'), ('simulation_measure', 'Измерение симуляции')], max_length=32)),
                ('title', models.CharField(max_length=180)),
                ('prompt', models.TextField()),
                ('rubric', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveSmallIntegerField(default=100)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='knowledge.learninglesson')),
            ],
            options={
                'verbose_name': 'Учебное задание',
                'verbose_name_plural': 'Учебные задания',
                'ordering': ['lesson__order', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_task_ids', models.JSONField(blank=True, default=list)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='knowledge.learninglesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогресс обучения',
                'verbose_name_plural': 'Прогресс обучения',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='knowledge_l_user_id_013f3e_idx')],
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='LearningAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(blank=True, default=dict)),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_attempts', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='knowledge.learningtask')),
            ],
            options={
                'verbose_name': 'Попытка учебного задания',
                'verbose_name_plural': 'Попытки учебных заданий',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='knowledge_l_user_id_adca81_idx')],
            },
        ),
    ]
