apiVersion: v1
kind: Namespace
metadata:
  name: dolg
  labels:
    app.kubernetes.io/name: dolg
    app.kubernetes.io/part-of: dolg-platform
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
