apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dolg-web-pdb
  labels:
    app.kubernetes.io/name: dolg
    app.kubernetes.io/component: web
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dolg
      app.kubernetes.io/component: web
