# Generated by Django 6.0.4 on 2026-05-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pro_logo',
            field=models.ImageField(blank=True, null=True, upload_to='pro_logos/'),
        ),
    ]
