# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_pro_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accent_color',
            field=models.CharField(
                choices=[
                    ('cyan', 'Бирюзовый'),
                    ('blue', 'Синий'),
                    ('green', 'Зеленый'),
                    ('orange', 'Оранжевый'),
                    ('violet', 'Фиолетовый'),
                ],
                default='cyan',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_tone',
            field=models.CharField(
                choices=[
                    ('concise', 'Кратко'),
                    ('explained', 'С объяснением'),
                    ('review', 'Инженерный review'),
                    ('demo', 'Для защиты'),
                ],
                default='explained',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_unit_system',
            field=models.CharField(
                choices=[
                    ('engineering', 'Инженерные единицы'),
                    ('metric', 'Метрические единицы'),
                ],
                default='engineering',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_theme',
            field=models.CharField(
                choices=[
                    ('dark', 'Темная'),
                    ('light', 'Светлая'),
                    ('system', 'Как в системе'),
                    ('projector', 'Для проектора'),
                ],
                default='dark',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_engineering_badges',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_profile_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='start_page',
            field=models.CharField(
                choices=[
                    ('catalog', 'Каталог'),
                    ('projects', 'Проекты'),
                    ('simulation', 'Симуляция'),
                    ('lab', 'Лаборатория'),
                    ('learning', 'Обучение'),
                ],
                default='catalog',
                max_length=20,
            ),
        ),
    ]
