# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_customization'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_ai_training',
            field=models.BooleanField(default=False),
        ),
    ]
