# Generated by Django 5.2.14 on 2026-06-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0005_userprofile_allow_ai_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_backend',
            field=models.CharField(
                choices=[
                    ('auto', 'Автоматически'),
                    ('local', 'Локальный AI'),
                    ('cloud', 'Облачный AI'),
                    ('disabled', 'Отключить AI'),
                ],
                default='auto',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enable_workspace_animations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interface_density',
            field=models.CharField(
                choices=[('compact', 'Компактно'), ('comfortable', 'Комфортно'), ('spacious', 'Свободно')],
                default='comfortable',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_render_mode',
            field=models.CharField(
                choices=[('auto', 'Автоматически'), ('canvas2d', 'Canvas 2D'), ('webgl', 'WebGL / Pixi')],
                default='auto',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_sim_engine',
            field=models.CharField(
                choices=[
                    ('auto', 'Автоматически'),
                    ('browser_ngspice', 'Browser NGSpice'),
                    ('pyspice', 'PySpice'),
                    ('xyce', 'Xyce'),
                    ('gnucap', 'GnuCap'),
                    ('openmodelica', 'OpenModelica'),
                ],
                default='auto',
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reduce_motion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_advanced_tools',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='workspace_layout',
            field=models.CharField(
                choices=[
                    ('balanced', 'Сбалансированно'),
                    ('focus', 'Фокус на холсте'),
                    ('lab', 'Лаборатория и приборы'),
                    ('review', 'Инженерное ревью'),
                ],
                default='balanced',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='workspace_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
