# Generated by Django 5.2.14 on 2026-06-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_ai_backend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ai_backend',
            field=models.CharField(choices=[('auto', 'Автоматически'), ('local', 'Локальный AI'), ('engine_ai', 'Локальный AI + движки'), ('disabled', 'Отключить AI')], default='auto', max_length=20),
        ),
    ]
