# Generated by Django 6.0.3 on 2026-04-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='datasheet_url',
            field=models.URLField(blank=True, verbose_name='Datasheet URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='lifecycle_status',
            field=models.CharField(choices=[('active', 'Active'), ('nrnd', 'NRND'), ('eol', 'EOL'), ('obsolete', 'Obsolete')], default='active', max_length=10, verbose_name='Lifecycle Status'),
        ),
        migrations.AddField(
            model_name='product',
            name='package_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Package / Корпус'),
        ),
        migrations.AddField(
            model_name='product',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, verbose_name='Технические параметры'),
        ),
        migrations.AddField(
            model_name='product',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Part Number / SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('sony', 'Sony'), ('lg', 'LG'), ('microsoft', 'Microsoft'), ('intel', 'Intel'), ('amd', 'AMD'), ('yageo', 'Yageo'), ('vishay', 'Vishay'), ('murata', 'Murata'), ('tdk', 'TDK'), ('kemet', 'KEMET'), ('st', 'STMicroelectronics'), ('nxp', 'NXP'), ('ti', 'Texas Instruments'), ('infineon', 'Infineon'), ('onsemi', 'onsemi'), ('bourns', 'Bourns'), ('panasonic', 'Panasonic'), ('nichicon', 'Nichicon'), ('wurth', 'Würth Elektronik'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
