# Generated by Django 6.0.3 on 2026-04-22 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchematicProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('led', 'LED проект'), ('audio', 'Аудио'), ('power', 'Блок питания'), ('sensor', 'Сенсор'), ('arduino', 'Arduino'), ('other', 'Другое')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('inprogress', 'В работе'), ('completed', 'Завершено')], default='draft', max_length=20)),
                ('scheme_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schematic_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
