# Generated by Django 6.0.4 on 2026-04-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dolg_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schematicproject',
            name='difficulty',
            field=models.CharField(choices=[('basic', 'Начальный'), ('medium', 'Средний'), ('advanced', 'Продвинутый')], default='basic', max_length=10),
        ),
        migrations.AddField(
            model_name='schematicproject',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
