# Generated by Django 6.0.4 on 2026-05-03 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dolg_APP', '0002_schematicproject_difficulty_schematicproject_is_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('dc', 'DC / рабочая точка'), ('op', 'Рабочая точка'), ('ac', 'АЧХ/ФЧХ'), ('tran', 'Переходный процесс'), ('pulse', 'Импульсный режим'), ('unknown', 'Неизвестно')], default='unknown', max_length=20)),
                ('engine', models.CharField(blank=True, max_length=80)),
                ('elapsed_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='success', max_length=20)),
                ('netlist', models.TextField(blank=True)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_runs', to='Dolg_APP.schematicproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запуск симуляции',
                'verbose_name_plural': 'Запуски симуляций',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('scheme_data', models.JSONField(blank=True, default=dict)),
                ('change_note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='Dolg_APP.schematicproject')),
            ],
            options={
                'verbose_name': 'Версия схемы',
                'verbose_name_plural': 'Версии схем',
                'ordering': ['-version_number'],
                'unique_together': {('project', 'version_number')},
            },
        ),
    ]
