# Generated by Django 6.0.4 on 2026-05-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dolg_APP', '0003_simulationrun_projectversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='schematicproject',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=22),
        ),
    ]
