# Generated by Django 6.0.4 on 2026-05-17 05:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dolg_APP', '0004_schematicproject_share_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schematicproject',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('simulations_count', models.PositiveIntegerField(default=0)),
                ('ai_requests_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Дневная активность',
                'verbose_name_plural': 'Дневная активность',
                'indexes': [models.Index(fields=['user', '-date'], name='Dolg_APP_da_user_id_57f1b0_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
