# Generated by Django 6.0.4 on 2026-05-17 13:24

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dolg_APP', '0005_schematicproject_deleted_at_dailyusage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schematicproject',
            options={'base_manager_name': 'all_objects', 'ordering': ['-updated_at']},
        ),
        migrations.AlterModelManagers(
            name='schematicproject',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
