# Generated by Codex on 2026-05-17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dolg_APP', '0006_alter_schematicproject_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('ready', 'ready'), ('needs_review', 'needs review'), ('risk', 'risk'), ('critical', 'critical')], default='needs_review', max_length=24)),
                ('summary', models.TextField(blank=True)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('sections', models.JSONField(blank=True, default=dict)),
                ('faults', models.JSONField(blank=True, default=list)),
                ('scheme_data', models.JSONField(blank=True, default=dict)),
                ('import_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Dolg_APP.schematicproject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='Dolg_APP_pr_project_f56f7f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=80)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=24)),
                ('expected_value', models.FloatField(blank=True, null=True)),
                ('tolerance_abs', models.FloatField(blank=True, null=True)),
                ('tolerance_percent', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='unchecked', max_length=24)),
                ('source', models.CharField(default='manual', max_length=40)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='Dolg_APP.schematicproject')),
                ('simulation_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='Dolg_APP.simulationrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='Dolg_APP_pr_project_93d531_idx')],
            },
        ),
    ]
