# Generated by Django 6.0.4 on 2026-05-17 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dolg_APP', '0007_projectmeasurement_projectreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=10)),
                ('status', models.CharField(choices=[('trial', 'Пробный период'), ('active', 'Активна'), ('cancelled', 'Отменена (доступ до конца периода)'), ('expired', 'Истекла')], default='active', max_length=12)),
                ('provider', models.CharField(choices=[('trial', '14-дневный trial'), ('manual', 'Выдано админом'), ('stripe', 'Stripe'), ('cloudpayments', 'CloudPayments')], default='manual', max_length=20)),
                ('period_start', models.DateTimeField(auto_now_add=True)),
                ('period_end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('trial_used', models.BooleanField(default=False, help_text='Trial уже использован — повторно нельзя на этот аккаунт.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
