# Generated by Django 6.0.4 on 2026-05-17 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dolg_APP', '0009_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schematicproject',
            name='approval_state',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending_review', 'На ревью'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='schematicproject',
            name='visibility',
            field=models.CharField(choices=[('private', 'Только владелец'), ('team', 'Видна команде'), ('public', 'Публичный marketplace')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('billing_email', models.EmailField(max_length=254)),
                ('plan', models.CharField(choices=[('team', 'Team (до 10 seats)'), ('business', 'Business (10-100 seats)'), ('enterprise', 'Enterprise (∞ seats)')], default='team', max_length=20)),
                ('seats_max', models.PositiveIntegerField(default=10)),
                ('storage_quota_bytes', models.BigIntegerField(default=107374182400)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('custom_logo', models.ImageField(blank=True, null=True, upload_to='org_logos/')),
                ('custom_color', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('team_size_range', models.CharField(max_length=30)),
                ('industry', models.CharField(blank=True, max_length=80)),
                ('requirements', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'Новая заявка'), ('contacted', 'Связались'), ('demo_scheduled', 'Демо запланировано'), ('proposal_sent', 'Предложение отправлено'), ('won', 'Закрыт успехом'), ('lost', 'Закрыт отказом')], db_index=True, default='new', max_length=20)),
                ('notes_internal', models.TextField(blank=True, help_text='Только для admin DOLG')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('converted_to_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Dolg_APP.organization')),
            ],
            options={
                'verbose_name': 'Enterprise-заявка',
                'verbose_name_plural': 'Enterprise-заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='schematicproject',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='Dolg_APP.organization'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='Dolg_APP.organization'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('object_type', models.CharField(blank=True, default='', max_length=40)),
                ('object_id', models.CharField(blank=True, default='', max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='Dolg_APP.organization')),
            ],
            options={
                'verbose_name': 'Запись audit-лога',
                'verbose_name_plural': 'Audit-лог',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['organization', '-timestamp'], name='Dolg_APP_au_organiz_3a2556_idx'), models.Index(fields=['actor', '-timestamp'], name='Dolg_APP_au_actor_i_dfacd1_idx'), models.Index(fields=['action', '-timestamp'], name='Dolg_APP_au_action_e36ac2_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('engineer', 'Инженер'), ('reviewer', 'Ревьюер'), ('viewer', 'Наблюдатель')], default='engineer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='Dolg_APP.organization')),
            ],
            options={
                'verbose_name': 'Приглашение в организацию',
                'verbose_name_plural': 'Приглашения в организацию',
                'indexes': [models.Index(fields=['organization', 'email'], name='Dolg_APP_or_organiz_6e96da_idx'), models.Index(fields=['expires_at'], name='Dolg_APP_or_expires_dfb6a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('engineer', 'Инженер'), ('reviewer', 'Ревьюер'), ('viewer', 'Наблюдатель')], default='engineer', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='Dolg_APP.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Член организации',
                'verbose_name_plural': 'Члены организации',
                'indexes': [models.Index(fields=['user', 'organization'], name='Dolg_APP_or_user_id_58a9ef_idx'), models.Index(fields=['organization', 'role'], name='Dolg_APP_or_organiz_b07fda_idx')],
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
