# Generated by Django 6.0.4 on 2026-05-18 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dolg_APP', '0010_schematicproject_approval_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Что использует токен (для аудита)', max_length=120)),
                ('token', models.CharField(db_index=True, max_length=80, unique=True)),
                ('scope', models.JSONField(blank=True, default=list)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='Dolg_APP.organization')),
            ],
            options={
                'verbose_name': 'API-токен организации',
                'verbose_name_plural': 'API-токены организации',
            },
        ),
    ]
