# Generated by Django 6.0.4 on 2026-05-18 21:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dolg_APP', '0011_organizationapitoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyusage',
            name='chat_replies_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyusage',
            name='chat_topics_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ChatTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('general', 'Общее'), ('schematics', 'Схемы'), ('simulation', 'Симуляция'), ('cad', 'CAD'), ('components', 'Компоненты РЭБ'), ('ai', 'AI-ассистент')], db_index=True, default='general', max_length=24)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('attached_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_topics', to='Dolg_APP.schematicproject')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_accepted_answer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_replies', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Dolg_APP.chatreply')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Dolg_APP.chattopic')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(default='👍', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='Dolg_APP.chatreply')),
                ('target_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='Dolg_APP.chattopic')),
            ],
        ),
        migrations.CreateModel(
            name='OrgConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('attached_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_conversations', to='Dolg_APP.schematicproject')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='Dolg_APP.organization')),
            ],
            options={
                'ordering': ['is_archived', '-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='OrgConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('mentions', models.JSONField(blank=True, default=list)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_messages', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Dolg_APP.orgconversation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Dolg_APP.orgconversationmessage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('level', models.CharField(choices=[('info', 'ℹ Информация'), ('warning', '⚠ Предупреждение'), ('critical', '🔴 Критично')], default='info', max_length=10)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Если задано — после этой даты объявление скрывается из сайдбара', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['is_published', '-created_at'], name='Dolg_APP_an_is_publ_ebbd4a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chattopic',
            index=models.Index(fields=['category', '-last_activity_at'], name='Dolg_APP_ch_categor_e0844b_idx'),
        ),
        migrations.AddIndex(
            model_name='chattopic',
            index=models.Index(fields=['-is_pinned', '-last_activity_at'], name='Dolg_APP_ch_is_pinn_3d55f7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatreply',
            index=models.Index(fields=['topic', 'created_at'], name='Dolg_APP_ch_topic_i_052e18_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('target_topic__isnull', False)), fields=('target_topic', 'user', 'emoji'), name='unique_topic_reaction'),
        ),
        migrations.AddConstraint(
            model_name='chatreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('target_reply__isnull', False)), fields=('target_reply', 'user', 'emoji'), name='unique_reply_reaction'),
        ),
        migrations.AddIndex(
            model_name='orgconversation',
            index=models.Index(fields=['organization', '-last_activity_at'], name='Dolg_APP_or_organiz_b7ed8a_idx'),
        ),
        migrations.AddIndex(
            model_name='orgconversationmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='Dolg_APP_or_convers_8b44de_idx'),
        ),
    ]
