# Generated by Django 6.0.4 on 2026-05-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dolg_APP', '0012_dailyusage_chat_replies_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
