# Generated by Django 6.0.4 on 2026-05-26 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dolg_APP', '0015_engineeringartifact_aitrainingexample'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatreply',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatreply',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatreply',
            name='moderation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chatreply',
            name='moderation_status',
            field=models.CharField(choices=[('visible', 'Видимый'), ('pending', 'На проверке'), ('hidden', 'Скрыт'), ('removed', 'Удален модератором')], db_index=True, default='visible', max_length=20),
        ),
        migrations.AddField(
            model_name='chattopic',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chattopic',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chattopic',
            name='moderation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chattopic',
            name='moderation_status',
            field=models.CharField(choices=[('visible', 'Видимый'), ('pending', 'На проверке'), ('hidden', 'Скрыт'), ('removed', 'Удален модератором')], db_index=True, default='visible', max_length=20),
        ),
        migrations.AddField(
            model_name='comment',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='moderation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='moderation_status',
            field=models.CharField(choices=[('visible', 'Видимый'), ('pending', 'На проверке'), ('hidden', 'Скрыт'), ('removed', 'Удален модератором')], db_index=True, default='visible', max_length=20),
        ),
        migrations.AddField(
            model_name='orgconversationmessage',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgconversationmessage',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orgconversationmessage',
            name='moderation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orgconversationmessage',
            name='moderation_status',
            field=models.CharField(choices=[('visible', 'Видимый'), ('pending', 'На проверке'), ('hidden', 'Скрыт'), ('removed', 'Удален модератором')], db_index=True, default='visible', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationinvite',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('engineer', 'Инженер'), ('reviewer', 'Ревьюер'), ('moderator', 'Модератор команды'), ('viewer', 'Наблюдатель')], default='engineer', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('engineer', 'Инженер'), ('reviewer', 'Ревьюер'), ('moderator', 'Модератор команды'), ('viewer', 'Наблюдатель')], default='engineer', max_length=20),
        ),
    ]
