# Generated by Django 5.2.14 on 2026-06-01 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dolg_APP', '0016_chatreply_moderated_at_chatreply_moderated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название блока (напр. "DC-DC 5В→3.3В")', max_length=80)),
                ('description', models.CharField(blank=True, help_text='Краткое описание для тултипа', max_length=200)),
                ('category', models.CharField(choices=[('power', '⚡ Питание'), ('analog', '🔊 Аналог'), ('digital', '💾 Цифра'), ('rf', '📡 РЧ'), ('filter', '🌊 Фильтры'), ('sensor', '🌡 Датчики'), ('other', '📦 Прочее')], default='other', max_length=16)),
                ('schema_json', models.JSONField(help_text='{"components":[...],"connections":[...]} формата applySchemeData')),
                ('preview_svg', models.TextField(blank=True, help_text='Опциональная мини-SVG-отрисовка')),
                ('is_public', models.BooleanField(db_index=True, default=False, help_text='Виден ли другим юзерам')),
                ('use_count', models.PositiveIntegerField(default=0, help_text='Счётчик использований (drag в схему)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Владелец блока', on_delete=django.db.models.deletion.CASCADE, related_name='functional_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='Dolg_APP_fu_user_id_b553c3_idx'), models.Index(fields=['is_public', 'category'], name='Dolg_APP_fu_is_publ_ed4bbe_idx')],
            },
        ),
    ]
