# Generated by Django 6.0.4 on 2026-05-26 00:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dolg_APP', '0016_chatreply_moderated_at_chatreply_moderated_by_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=64)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('organization', 'Organization')], db_index=True, default='global', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], db_index=True, default='open', max_length=20)),
                ('summary', models.CharField(blank=True, max_length=240)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_moderation_cases', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_moderation_cases', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_cases', to='Dolg_APP.organization')),
            ],
            options={
                'verbose_name': 'Moderation case',
                'verbose_name_plural': 'Moderation cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('hide', 'Hide'), ('restore', 'Restore'), ('remove', 'Remove'), ('warn', 'Warn'), ('mute', 'Mute'), ('ban', 'Ban'), ('read_only', 'Read only'), ('mark_reviewed', 'Mark reviewed'), ('reject_report', 'Reject report')], db_index=True, max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='moderation.moderationcase')),
            ],
            options={
                'verbose_name': 'Moderation action',
                'verbose_name_plural': 'Moderation actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('abuse', 'Abuse'), ('unsafe', 'Unsafe'), ('wrong_data', 'Wrong data'), ('offtopic', 'Offtopic'), ('other', 'Other')], default='other', max_length=32)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='moderation.moderationcase')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moderation report',
                'verbose_name_plural': 'Moderation reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('organization', 'Organization')], default='global', max_length=20)),
                ('applies_to', models.CharField(blank=True, help_text='Example: comment, chat, product', max_length=80)),
                ('action', models.CharField(blank=True, help_text='Example: hide, warn, needs_review', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_moderation_rules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_rules', to='Dolg_APP.organization')),
            ],
            options={
                'verbose_name': 'Moderation rule',
                'verbose_name_plural': 'Moderation rules',
                'ordering': ['scope', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction_type', models.CharField(choices=[('mute', 'Mute'), ('ban', 'Ban'), ('read_only', 'Read only')], db_index=True, max_length=20)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('organization', 'Organization')], db_index=True, default='global', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('lifted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user_restrictions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_restrictions', to='Dolg_APP.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User restriction',
                'verbose_name_plural': 'User restrictions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['status', '-created_at'], name='moderation__status_00f300_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['scope', 'status'], name='moderation__scope_1b453b_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['content_type', 'object_id'], name='moderation__content_7c5992_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['action_type', '-created_at'], name='moderation__action__989271_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationreport',
            index=models.Index(fields=['status', '-created_at'], name='moderation__status_bfb2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='userrestriction',
            index=models.Index(fields=['user', 'restriction_type', 'scope'], name='moderation__user_id_563fda_idx'),
        ),
        migrations.AddIndex(
            model_name='userrestriction',
            index=models.Index(fields=['scope', 'organization'], name='moderation__scope_4fe93d_idx'),
        ),
    ]
