"""Расширение DRC-правил до ~110. 2026-05-31.

Берёт существующий Dolg_APP/expert_rules/default_rules.json (13 правил),
добавляет новые правила из 12 категорий до общего количества ~110.

Правила собраны из открытых источников:
- KiCad ERC (eeschema/erc.cpp) — schematic electrical checks
- IPC-2221A / IPC-A-610 — board design + assembly standards
- OpenSPICE check_options — DC convergence + modeling
- Industry datasheet practices — BC547 Vceo, LED 20mA, electrolytic polarity
- Academic: "DRC for Analog ICs" (IEEE)

Каждое правило имеет:
  id, category, severity, title, recommendation, evidence_fields, when,
  enabled, source, confidence, references

`enabled: true` — implemented в expert_detectors.py / runQuickDRC.
`enabled: false` — declared but planned. Юзер видит в Review-модалке как
«доступно, будет реализовано в Phase 2».
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RULES_FILE = ROOT / 'Dolg_APP' / 'expert_rules' / 'default_rules.json'

NEW_RULES = [
    # ─── A. CONNECTIVITY (после уже существующих) ──────────────────────────
    {
        'id': 'conn.crossing_without_dot',
        'category': 'connectivity',
        'severity': 'warning',
        'title': 'Пересечение проводов без junction-dot',
        'recommendation': 'Если провода соединяются — добавьте узел (Node). Если только пересекаются — разведите их.',
        'when': 'crossing_count > 0 and explicit_node_count < crossing_count',
        'evidence_fields': ['crossing_count', 'explicit_node_count'],
        'enabled': False,
        'source': 'KiCad ERC',
        'confidence': 0.85,
    },
    {
        'id': 'conn.parallel_close_wires',
        'category': 'connectivity',
        'severity': 'recommendation',
        'title': 'Параллельные провода слишком близко (< 4 px)',
        'recommendation': 'Разнесите параллельные провода — на печати они визуально сольются.',
        'when': 'min_wire_spacing_px < 4',
        'evidence_fields': ['min_wire_spacing_px'],
        'enabled': False,
        'source': 'KiCad design hint',
        'confidence': 0.7,
    },
    {
        'id': 'conn.micro_segment',
        'category': 'connectivity',
        'severity': 'recommendation',
        'title': 'Микро-сегмент провода (< 5 px) — мусор от плохого роутинга',
        'recommendation': 'Удалите короткий сегмент или объедините с соседним.',
        'when': 'min_segment_length_px < 5',
        'evidence_fields': ['min_segment_length_px'],
        'enabled': False,
        'source': 'KiCad cleanup',
        'confidence': 0.8,
    },
    {
        'id': 'conn.floating_named_net',
        'category': 'connectivity',
        'severity': 'warning',
        'title': 'Висячая именованная цепь (net label без компонентов)',
        'recommendation': 'Удалите неиспользуемое имя net\'а или подключите компонент.',
        'when': 'orphan_net_label_count > 0',
        'evidence_fields': ['orphan_net_label_count'],
        'enabled': False,
        'source': 'KiCad ERC',
        'confidence': 0.9,
    },
    {
        'id': 'conn.single_connection_component',
        'category': 'connectivity',
        'severity': 'error',
        'title': 'Компонент подключён только одним пином — цепь разорвана',
        'recommendation': 'Подключите оба порта компонента к схеме.',
        'when': 'single_port_components > 0',
        'evidence_fields': ['single_port_components'],
        'enabled': True,
        'source': 'KiCad ERC',
        'confidence': 0.97,
    },
    {
        'id': 'conn.dangling_port',
        'category': 'connectivity',
        'severity': 'warning',
        'title': 'Висячий порт компонента',
        'recommendation': 'Подключите все пины или явно пометьте «no-connect».',
        'when': 'dangling_port_count > 0',
        'evidence_fields': ['dangling_port_count'],
        'enabled': True,
        'source': 'KiCad ERC',
        'confidence': 0.95,
    },
    {
        'id': 'conn.disjoint_islands',
        'category': 'connectivity',
        'severity': 'warning',
        'title': 'Схема разбита на несвязанные «острова»',
        'recommendation': 'Соедините острова в один граф или удалите неиспользуемые куски.',
        'when': 'connected_components_count > 1',
        'evidence_fields': ['connected_components_count'],
        'enabled': False,
        'source': 'KiCad ERC',
        'confidence': 0.9,
    },
    {
        'id': 'conn.multiple_gnd_different_nets',
        'category': 'connectivity',
        'severity': 'recommendation',
        'title': 'Несколько GND-компонентов в разных net\'ах',
        'recommendation': 'Если это намеренное разделение AGND/DGND — добавьте net-label. Иначе объедините в один net.',
        'when': 'ground_net_count > 1',
        'evidence_fields': ['ground_net_count'],
        'enabled': False,
        'source': 'Industry analog/digital ground split',
        'confidence': 0.65,
    },
    {
        'id': 'conn.duplicate_wire',
        'category': 'connectivity',
        'severity': 'recommendation',
        'title': 'Дублирующиеся провода между одними и теми же портами',
        'recommendation': 'Удалите дубликат — это «мёртвый» wire.',
        'when': 'duplicate_wires > 0',
        'evidence_fields': ['duplicate_wires'],
        'enabled': False,
        'source': 'KiCad cleanup',
        'confidence': 0.95,
    },

    # ─── B. SOURCE / POWER ────────────────────────────────────────────────
    {
        'id': 'power.source_to_gnd_short',
        'category': 'power',
        'severity': 'error',
        'title': 'Источник напрямую к GND без резистора (КЗ через источник)',
        'recommendation': 'Добавьте токоограничивающий резистор между + источника и GND.',
        'when': 'has_source_gnd_short == true',
        'evidence_fields': ['short_circuit_path'],
        'enabled': False,
        'source': 'Industry safety',
        'confidence': 0.95,
    },
    {
        'id': 'power.parallel_voltage_same_level',
        'category': 'power',
        'severity': 'warning',
        'title': 'Параллельные V-источники одного потенциала',
        'recommendation': 'Если намеренно — добавьте балансные резисторы. Иначе — один источник достаточен.',
        'when': 'parallel_voltage_sources > 0 and parallel_voltage_difference == 0',
        'evidence_fields': ['parallel_voltage_sources', 'parallel_voltage_difference'],
        'enabled': False,
        'source': 'Industry redundant power design',
        'confidence': 0.75,
    },
    {
        'id': 'power.source_no_return_path',
        'category': 'power',
        'severity': 'error',
        'title': 'Источник без обратного провода к GND',
        'recommendation': 'Подключите минус источника к GND через нагрузку — open circuit невозможен.',
        'when': 'source_without_return > 0',
        'evidence_fields': ['source_without_return'],
        'enabled': False,
        'source': 'OpenSPICE check',
        'confidence': 0.95,
    },
    {
        'id': 'power.battery_reverse_polarity',
        'category': 'power',
        'severity': 'error',
        'title': 'Батарея подключена обратной полярностью к нагрузке',
        'recommendation': 'Поменяйте местами + и − выводы батареи.',
        'when': 'reverse_battery_polarity > 0',
        'evidence_fields': ['reverse_battery_polarity'],
        'enabled': False,
        'source': 'Industry safety',
        'confidence': 0.85,
    },
    {
        'id': 'power.current_source_open_loop',
        'category': 'power',
        'severity': 'error',
        'title': 'Источник тока без замкнутой петли',
        'recommendation': 'Ток должен идти по замкнутому контуру (Кирхгофа). Добавьте обратный путь.',
        'when': 'current_source_open_loop > 0',
        'evidence_fields': ['current_source_open_loop'],
        'enabled': False,
        'source': 'OpenSPICE',
        'confidence': 0.95,
    },
    {
        'id': 'power.ac_without_dc_bias',
        'category': 'power',
        'severity': 'recommendation',
        'title': 'AC-источник без DC-bias компонента в цепи',
        'recommendation': 'Для аналоговых сигналов добавьте конденсатор связи и резистор смещения.',
        'when': 'has_ac_source == true and has_dc_bias_component == false',
        'evidence_fields': ['has_ac_source', 'has_dc_bias_component'],
        'enabled': False,
        'source': 'Industry analog design',
        'confidence': 0.6,
    },
    {
        'id': 'power.opposing_sources_same_net',
        'category': 'power',
        'severity': 'error',
        'title': 'Источники противоположной полярности на одном net\'е',
        'recommendation': 'Это создаёт неопределённый потенциал. Развяжите через изоляцию или диоды.',
        'when': 'opposing_sources_count > 0',
        'evidence_fields': ['opposing_sources_count'],
        'enabled': False,
        'source': 'KiCad ERC',
        'confidence': 0.9,
    },
    {
        'id': 'power.no_decoupling_near_ic',
        'category': 'power',
        'severity': 'recommendation',
        'title': 'Нет декаплинг-конденсатора около ICs/транзисторов',
        'recommendation': 'Добавьте 100 нФ + 10 мкФ керамический рядом с каждым активным компонентом.',
        'when': 'active_components_without_decoupling > 0',
        'evidence_fields': ['active_components_without_decoupling'],
        'enabled': False,
        'source': 'Industry analog/digital practice',
        'confidence': 0.7,
    },

    # ─── C. POLARIZED COMPONENTS ──────────────────────────────────────────
    {
        'id': 'polarity.electrolytic_reverse',
        'category': 'polarity',
        'severity': 'error',
        'title': 'Электролитический конденсатор обратной полярности на DC',
        'recommendation': 'Анод (+) должен быть на более высоком потенциале. В реальности это приводит к взрыву!',
        'when': 'reverse_electrolytic_count > 0',
        'evidence_fields': ['reverse_electrolytic_count'],
        'enabled': False,
        'source': 'IPC-A-610',
        'confidence': 0.9,
    },
    {
        'id': 'polarity.diode_reverse_in_rectifier',
        'category': 'polarity',
        'severity': 'error',
        'title': 'Диод обратной полярности в выпрямительной схеме',
        'recommendation': 'Анод диода к +, катод к нагрузке. Стрелка диода = направление тока.',
        'when': 'reverse_rectifier_diode_count > 0',
        'evidence_fields': ['reverse_rectifier_diode_count'],
        'enabled': False,
        'source': 'Industry rectifier topology',
        'confidence': 0.85,
    },
    {
        'id': 'polarity.led_reverse',
        'category': 'polarity',
        'severity': 'error',
        'title': 'LED подключён обратной полярностью',
        'recommendation': 'Анод (длинный вывод) — к плюсу через резистор, катод — к минусу.',
        'when': 'reverse_led_count > 0',
        'evidence_fields': ['reverse_led_count'],
        'enabled': False,
        'source': 'IPC-A-610',
        'confidence': 0.9,
    },
    {
        'id': 'polarity.tantalum_voltage_derating',
        'category': 'polarity',
        'severity': 'warning',
        'title': 'Танталовый конденсатор без 50% derating',
        'recommendation': 'Танталовые требуют V_applied ≤ 0.5 × V_rated для надёжности (взрывоопасны).',
        'when': 'has_tantalum == true and tantalum_derating < 0.5',
        'evidence_fields': ['tantalum_derating'],
        'enabled': False,
        'source': 'Industry tantalum practice',
        'confidence': 0.8,
    },
    {
        'id': 'polarity.bjt_be_swap_heuristic',
        'category': 'polarity',
        'severity': 'warning',
        'title': 'Транзистор BJT: эвристика перепутанных Base/Emitter',
        'recommendation': 'Проверьте: ток базы (через R) идёт в base, эмиттер обычно к GND через R или напрямую.',
        'when': 'bjt_pinout_suspicious_count > 0',
        'evidence_fields': ['bjt_pinout_suspicious_count'],
        'enabled': False,
        'source': 'Industry common mistake',
        'confidence': 0.55,
    },
    {
        'id': 'polarity.zener_forward_biased',
        'category': 'polarity',
        'severity': 'recommendation',
        'title': 'Zener-диод в прямом смещении (работает как обычный диод)',
        'recommendation': 'Для стабилизации Zener должен быть включён в обратном смещении.',
        'when': 'zener_forward_count > 0',
        'evidence_fields': ['zener_forward_count'],
        'enabled': False,
        'source': 'Industry zener practice',
        'confidence': 0.75,
    },

    # ─── D. COMPONENT RATINGS ──────────────────────────────────────────────
    {
        'id': 'rating.voltage_exceeded',
        'category': 'rating',
        'severity': 'error',
        'title': 'Превышен максимальный V компонента',
        'recommendation': 'Замените компонент на более высоковольтный или снизьте рабочее напряжение.',
        'when': 'voltage_rating_violations > 0',
        'evidence_fields': ['voltage_rating_violations'],
        'enabled': True,
        'source': 'IPC-2221',
        'confidence': 0.95,
    },
    {
        'id': 'rating.current_through_resistor',
        'category': 'rating',
        'severity': 'error',
        'title': 'Ток через резистор превышает P_max',
        'recommendation': 'P = I²R должно быть < rating (1/4W = 0.25Вт). Увеличьте мощность резистора.',
        'when': 'resistor_power_violation_count > 0',
        'evidence_fields': ['resistor_power_violation_count'],
        'enabled': False,
        'source': 'Industry resistor practice',
        'confidence': 0.95,
    },
    {
        'id': 'rating.capacitor_voltage_with_ac_peak',
        'category': 'rating',
        'severity': 'warning',
        'title': 'V_DC + V_AC_peak конденсатора превышает rated',
        'recommendation': 'Учтите пик AC-сигнала на DC-bias\'е. Возьмите конденсатор с запасом 50%.',
        'when': 'cap_v_peak_exceeded > 0',
        'evidence_fields': ['cap_v_peak_exceeded'],
        'enabled': False,
        'source': 'Industry derating practice',
        'confidence': 0.85,
    },
    {
        'id': 'rating.transistor_vceo',
        'category': 'rating',
        'severity': 'error',
        'title': 'Транзистор: V_CE превышает V_CEO',
        'recommendation': 'Замените транзистор на более высоковольтный (например 2N3904 → BC517).',
        'when': 'bjt_vceo_exceeded > 0',
        'evidence_fields': ['bjt_vceo_exceeded'],
        'enabled': False,
        'source': 'BC547 datasheet',
        'confidence': 0.95,
    },
    {
        'id': 'rating.diode_reverse_voltage',
        'category': 'rating',
        'severity': 'error',
        'title': 'Диод: обратное напряжение > V_BR',
        'recommendation': 'Возьмите диод с большим V_BR (1N4148 → 1N4007).',
        'when': 'diode_vbr_exceeded > 0',
        'evidence_fields': ['diode_vbr_exceeded'],
        'enabled': False,
        'source': '1N4148 datasheet',
        'confidence': 0.9,
    },
    {
        'id': 'rating.led_current_overdrive',
        'category': 'rating',
        'severity': 'warning',
        'title': 'LED-ток > 20 mA (нагрев / выгорание)',
        'recommendation': 'Стандартный LED — 20 мА. Для high-power добавьте теплоотвод или используйте LED-driver.',
        'when': 'led_overdrive_count > 0',
        'evidence_fields': ['led_overdrive_count'],
        'enabled': False,
        'source': 'Industry LED practice',
        'confidence': 0.9,
    },
    {
        'id': 'rating.resistor_dissipation_class',
        'category': 'rating',
        'severity': 'recommendation',
        'title': 'Резистор работает на > 50% от P_max (низкий derating)',
        'recommendation': 'Для надёжности возьмите резистор большей мощности (derating 50%).',
        'when': 'resistor_low_derating > 0',
        'evidence_fields': ['resistor_low_derating'],
        'enabled': False,
        'source': 'IPC-2221 derating',
        'confidence': 0.75,
    },
    {
        'id': 'rating.inductor_saturation',
        'category': 'rating',
        'severity': 'error',
        'title': 'Ток через индуктор превышает I_sat',
        'recommendation': 'Замените на индуктор с большим saturation current.',
        'when': 'inductor_isat_exceeded > 0',
        'evidence_fields': ['inductor_isat_exceeded'],
        'enabled': False,
        'source': 'Coilcraft inductor practice',
        'confidence': 0.9,
    },

    # ─── E. TOPOLOGY / DESIGN PATTERNS ────────────────────────────────────
    {
        'id': 'topology.opamp_no_feedback',
        'category': 'topology',
        'severity': 'error',
        'title': 'Op-amp без feedback (open-loop)',
        'recommendation': 'Для линейной работы op-amp нужен feedback от выхода ко входу.',
        'when': 'opamp_no_feedback_count > 0',
        'evidence_fields': ['opamp_no_feedback_count'],
        'enabled': False,
        'source': 'KiCad ERC',
        'confidence': 0.9,
    },
    {
        'id': 'topology.opamp_input_rail_violation',
        'category': 'topology',
        'severity': 'warning',
        'title': 'Op-amp: входы за пределами питания (V_in > V_supply)',
        'recommendation': 'Используйте rail-to-rail op-amp или добавьте делитель.',
        'when': 'opamp_input_rail_violations > 0',
        'evidence_fields': ['opamp_input_rail_violations'],
        'enabled': False,
        'source': 'Industry analog design',
        'confidence': 0.85,
    },
    {
        'id': 'topology.digital_pin_no_pullup',
        'category': 'topology',
        'severity': 'warning',
        'title': 'Цифровой вход без pull-up/pull-down резистора',
        'recommendation': 'Добавьте pull-up 10к к VCC или pull-down 10к к GND.',
        'when': 'floating_digital_inputs > 0',
        'evidence_fields': ['floating_digital_inputs'],
        'enabled': False,
        'source': 'KiCad ERC',
        'confidence': 0.85,
    },
    {
        'id': 'topology.asymmetric_divider_for_ac',
        'category': 'topology',
        'severity': 'recommendation',
        'title': 'Несимметричный делитель напряжения для AC (отсечение)',
        'recommendation': 'Для AC-сигнала bias-точка должна быть в середине рабочего диапазона.',
        'when': 'ac_divider_asymmetry > 0.3',
        'evidence_fields': ['ac_divider_asymmetry'],
        'enabled': False,
        'source': 'Industry analog signal chain',
        'confidence': 0.7,
    },
    {
        'id': 'topology.rc_filter_resonance',
        'category': 'topology',
        'severity': 'recommendation',
        'title': 'RC-фильтр в зоне резонанса (риск self-oscillation)',
        'recommendation': 'Проверьте Q-factor — для filter\'ов Q < 1 безопасно.',
        'when': 'rc_q_factor > 1.0',
        'evidence_fields': ['rc_q_factor'],
        'enabled': False,
        'source': 'Academic analog filter',
        'confidence': 0.6,
    },
    {
        'id': 'topology.crystal_no_load_caps',
        'category': 'topology',
        'severity': 'error',
        'title': 'Кварцевый резонатор без load-конденсаторов',
        'recommendation': 'Добавьте 18-22 пФ конденсаторы от каждого вывода кварца к GND.',
        'when': 'crystal_without_load_caps > 0',
        'evidence_fields': ['crystal_without_load_caps'],
        'enabled': False,
        'source': 'Industry oscillator design',
        'confidence': 0.95,
    },
    {
        'id': 'topology.reset_pin_no_pullup',
        'category': 'topology',
        'severity': 'error',
        'title': 'Reset-pin без pull-up + капа',
        'recommendation': 'Reset обычно: pull-up 10к + 100 нФ к GND + кнопка к GND.',
        'when': 'reset_pin_floating == true',
        'evidence_fields': ['reset_pin_floating'],
        'enabled': False,
        'source': 'Industry MCU practice',
        'confidence': 0.85,
    },
    {
        'id': 'topology.differential_pair_unmatched',
        'category': 'topology',
        'severity': 'warning',
        'title': 'Differential pair с разной длиной/импедансом',
        'recommendation': 'USB/HDMI/LVDS требуют length-matching < 5%.',
        'when': 'diff_pair_mismatch > 0.05',
        'evidence_fields': ['diff_pair_mismatch'],
        'enabled': False,
        'source': 'IPC-2141 differential routing',
        'confidence': 0.85,
    },
    {
        'id': 'topology.signal_to_noise_ratio_low',
        'category': 'topology',
        'severity': 'recommendation',
        'title': 'Низкий SNR: сигнал слабый относительно шума',
        'recommendation': 'Усильте сигнал на входе (op-amp gain stage) перед обработкой.',
        'when': 'estimated_snr_db < 30',
        'evidence_fields': ['estimated_snr_db'],
        'enabled': False,
        'source': 'Academic signal integrity',
        'confidence': 0.6,
    },
    {
        'id': 'topology.feedback_loop_gain_excess',
        'category': 'topology',
        'severity': 'warning',
        'title': 'Усиление feedback-контура > 80 dB (риск oscillation)',
        'recommendation': 'Уменьшите gain или добавьте compensation cap.',
        'when': 'loop_gain_db > 80',
        'evidence_fields': ['loop_gain_db'],
        'enabled': False,
        'source': 'Academic control theory',
        'confidence': 0.7,
    },
    {
        'id': 'topology.no_input_protection',
        'category': 'topology',
        'severity': 'recommendation',
        'title': 'Внешний вход без TVS/ESD-защиты',
        'recommendation': 'Добавьте TVS-диод и/или RC-фильтр на внешних портах.',
        'when': 'unprotected_external_input_count > 0',
        'evidence_fields': ['unprotected_external_input_count'],
        'enabled': False,
        'source': 'IPC-2221A ESD',
        'confidence': 0.7,
    },

    # ─── F. SIGNAL INTEGRITY ──────────────────────────────────────────────
    {
        'id': 'signal.unterminated_high_speed',
        'category': 'signal',
        'severity': 'warning',
        'title': 'Высокоскоростной сигнал без согласующего резистора',
        'recommendation': 'Для линий > 50 МГц добавьте источник- или нагрузочное согласование (50/75/100 Ω).',
        'when': 'high_speed_unterminated > 0',
        'evidence_fields': ['high_speed_unterminated'],
        'enabled': False,
        'source': 'Industry SI design',
        'confidence': 0.85,
    },
    {
        'id': 'signal.clock_no_series_resistor',
        'category': 'signal',
        'severity': 'recommendation',
        'title': 'Линия CLK без serial-резистора (риск ringing)',
        'recommendation': 'Добавьте 22-33 Ω в серии для damping.',
        'when': 'clock_no_damping > 0',
        'evidence_fields': ['clock_no_damping'],
        'enabled': False,
        'source': 'IPC-2152 clock routing',
        'confidence': 0.75,
    },
    {
        'id': 'signal.long_unbuffered_trace',
        'category': 'signal',
        'severity': 'recommendation',
        'title': 'Длинная (> 100 мм) непробуференная сигнальная линия',
        'recommendation': 'Используйте buffer (74LVC1G125) или дифпару.',
        'when': 'long_unbuffered_traces > 0',
        'evidence_fields': ['long_unbuffered_traces'],
        'enabled': False,
        'source': 'Industry buffer practice',
        'confidence': 0.65,
    },
    {
        'id': 'signal.crosstalk_risk',
        'category': 'signal',
        'severity': 'recommendation',
        'title': 'Возможный crosstalk между параллельными high-speed линиями',
        'recommendation': 'Разнесите линии или добавьте GND-trace между ними.',
        'when': 'parallel_high_speed_pairs > 0',
        'evidence_fields': ['parallel_high_speed_pairs'],
        'enabled': False,
        'source': 'IPC-2141',
        'confidence': 0.65,
    },
    {
        'id': 'signal.ground_bounce_risk',
        'category': 'signal',
        'severity': 'recommendation',
        'title': 'Риск ground bounce от групповой коммутации',
        'recommendation': 'Добавьте отдельные GND-vias около каждого MCU/FPGA пина.',
        'when': 'simultaneous_switching_outputs > 8',
        'evidence_fields': ['simultaneous_switching_outputs'],
        'enabled': False,
        'source': 'Academic digital design',
        'confidence': 0.6,
    },
    {
        'id': 'signal.reflection_at_stub',
        'category': 'signal',
        'severity': 'warning',
        'title': 'Stub-ветвление на high-speed линии',
        'recommendation': 'Избегайте Y-ветвлений на линиях > 10 МГц.',
        'when': 'high_speed_stubs > 0',
        'evidence_fields': ['high_speed_stubs'],
        'enabled': False,
        'source': 'IPC-2141',
        'confidence': 0.8,
    },

    # ─── G. BOM / CATALOG ─────────────────────────────────────────────────
    {
        'id': 'bom.unbound_components',
        'category': 'bom',
        'severity': 'recommendation',
        'title': 'Компоненты без привязки к каталогу',
        'recommendation': 'Привяжите компоненты к товарам каталога для авто-BOM и заказа.',
        'when': 'unbound_component_count > 0',
        'evidence_fields': ['unbound_component_count'],
        'enabled': True,
        'source': 'DOLG BOM workflow',
        'confidence': 0.9,
    },
    {
        'id': 'bom.lifecycle_eol',
        'category': 'bom',
        'severity': 'warning',
        'title': 'Компонент в каталоге помечен EOL (End of Life)',
        'recommendation': 'Замените на актуальный аналог.',
        'when': 'eol_component_count > 0',
        'evidence_fields': ['eol_component_count'],
        'enabled': False,
        'source': 'DOLG catalog metadata',
        'confidence': 0.95,
    },
    {
        'id': 'bom.out_of_stock',
        'category': 'bom',
        'severity': 'recommendation',
        'title': 'Компонент out-of-stock в каталоге',
        'recommendation': 'Подберите аналог или подождите поступления.',
        'when': 'oos_component_count > 0',
        'evidence_fields': ['oos_component_count'],
        'enabled': False,
        'source': 'DOLG catalog stock',
        'confidence': 0.95,
    },
    {
        'id': 'bom.category_mismatch',
        'category': 'bom',
        'severity': 'warning',
        'title': 'Категория компонента не соответствует типу схемы',
        'recommendation': 'Проверьте: возможно SMD vs THT перепутаны.',
        'when': 'bom_category_mismatch_count > 0',
        'evidence_fields': ['bom_category_mismatch_count'],
        'enabled': False,
        'source': 'DOLG BOM logic',
        'confidence': 0.75,
    },
    {
        'id': 'bom.high_cost_warning',
        'category': 'bom',
        'severity': 'recommendation',
        'title': 'BOM > 5000 ₽ — возможно есть дешевле аналоги',
        'recommendation': 'Запустите AI-поиск аналогов через кнопку 🔍 Analogs.',
        'when': 'total_bom_cost > 5000',
        'evidence_fields': ['total_bom_cost'],
        'enabled': False,
        'source': 'DOLG cost optimisation',
        'confidence': 0.6,
    },
    {
        'id': 'bom.no_spice_model',
        'category': 'bom',
        'severity': 'recommendation',
        'title': 'Активный компонент без SPICE-модели',
        'recommendation': 'Для точной симуляции загрузите .lib или .mod от производителя.',
        'when': 'active_components_without_spice > 0',
        'evidence_fields': ['active_components_without_spice'],
        'enabled': False,
        'source': 'ngspice modeling',
        'confidence': 0.85,
    },
    {
        'id': 'bom.duplicate_designators',
        'category': 'bom',
        'severity': 'error',
        'title': 'Дублирующиеся designators (R1, R1)',
        'recommendation': 'Перенумеруйте компоненты — каждый должен иметь уникальный designator.',
        'when': 'duplicate_designator_count > 0',
        'evidence_fields': ['duplicate_designator_count'],
        'enabled': False,
        'source': 'KiCad ERC',
        'confidence': 0.95,
    },

    # ─── H. SIMULATION HYGIENE ────────────────────────────────────────────
    {
        'id': 'simulation.no_measurements',
        'category': 'simulation',
        'severity': 'recommendation',
        'title': 'В проекте нет сохранённых измерений',
        'recommendation': 'Сохраните expected vs measured пары для регрессии.',
        'when': 'measurement_count == 0 and component_count > 3',
        'evidence_fields': ['measurement_count'],
        'enabled': True,
        'source': 'DOLG project review',
        'confidence': 0.85,
    },
    {
        'id': 'simulation.dc_convergence_unstable',
        'category': 'simulation',
        'severity': 'warning',
        'title': 'DC-симуляция не сошлась — нужны .options',
        'recommendation': 'Попробуйте .options gmin=1e-9, increase iteration limit.',
        'when': 'dc_no_convergence == true',
        'evidence_fields': ['dc_no_convergence'],
        'enabled': False,
        'source': 'ngspice docs',
        'confidence': 0.95,
    },
    {
        'id': 'simulation.tran_step_too_large',
        'category': 'simulation',
        'severity': 'warning',
        'title': 'TRAN: шаг > 1/100 от наименьшего постоянного времени',
        'recommendation': 'Уменьшите .tran step для аккуратности.',
        'when': 'tran_step_ratio > 0.01',
        'evidence_fields': ['tran_step_ratio'],
        'enabled': False,
        'source': 'ngspice TRAN guide',
        'confidence': 0.8,
    },
    {
        'id': 'simulation.ac_sweep_too_narrow',
        'category': 'simulation',
        'severity': 'recommendation',
        'title': 'AC sweep охватывает < 3 декад',
        'recommendation': 'Расширьте sweep до 4-6 декад для полной АЧХ.',
        'when': 'ac_sweep_decades < 3',
        'evidence_fields': ['ac_sweep_decades'],
        'enabled': False,
        'source': 'Bode plot practice',
        'confidence': 0.7,
    },
    {
        'id': 'simulation.unrealistic_components',
        'category': 'simulation',
        'severity': 'warning',
        'title': 'Нереалистичные значения R/C/L (например R=0)',
        'recommendation': 'Замените 0 на 1mΩ — иначе SPICE даст бесконечный ток.',
        'when': 'unrealistic_value_count > 0',
        'evidence_fields': ['unrealistic_value_count'],
        'enabled': False,
        'source': 'ngspice numerical stability',
        'confidence': 0.95,
    },
    {
        'id': 'simulation.missing_initial_conditions',
        'category': 'simulation',
        'severity': 'recommendation',
        'title': 'TRAN без initial conditions для индукторов/конденсаторов',
        'recommendation': 'Добавьте .ic V(node)=… для предсказуемого start.',
        'when': 'tran_no_ic == true and has_reactive_components == true',
        'evidence_fields': ['tran_no_ic', 'has_reactive_components'],
        'enabled': False,
        'source': 'ngspice TRAN best practices',
        'confidence': 0.7,
    },

    # ─── I. DOCUMENTATION / METADATA ──────────────────────────────────────
    {
        'id': 'docs.no_project_description',
        'category': 'docs',
        'severity': 'recommendation',
        'title': 'У проекта нет описания',
        'recommendation': 'Добавьте описание — что эта схема делает.',
        'when': 'project_description_empty == true',
        'evidence_fields': ['project_description_empty'],
        'enabled': True,
        'source': 'DOLG project hygiene',
        'confidence': 0.95,
    },
    {
        'id': 'docs.unlabeled_components',
        'category': 'docs',
        'severity': 'recommendation',
        'title': 'Компоненты без подписей (label пустой)',
        'recommendation': 'Подпишите R1/C2/V1 для читаемости.',
        'when': 'unlabeled_component_count > 0',
        'evidence_fields': ['unlabeled_component_count'],
        'enabled': False,
        'source': 'KiCad style guide',
        'confidence': 0.9,
    },
    {
        'id': 'docs.no_net_labels',
        'category': 'docs',
        'severity': 'recommendation',
        'title': 'Схема без net-labels для важных узлов',
        'recommendation': 'Назовите VCC/GND/OUT/CLK явно — упрощает отладку.',
        'when': 'named_net_count < 2 and component_count > 5',
        'evidence_fields': ['named_net_count'],
        'enabled': False,
        'source': 'Industry schematic readability',
        'confidence': 0.7,
    },

    # ─── J. LAYOUT / PCB HINTS ────────────────────────────────────────────
    {
        'id': 'layout.trace_width_too_narrow',
        'category': 'layout',
        'severity': 'warning',
        'title': 'Trace width слишком узкая для рассчитанного тока',
        'recommendation': 'IPC-2221: I = k × T^0.44 × A^0.725 (1A = 0.4 мм для 35 мкм).',
        'when': 'trace_width_violations > 0',
        'evidence_fields': ['trace_width_violations'],
        'enabled': False,
        'source': 'IPC-2221A',
        'confidence': 0.9,
    },
    {
        'id': 'layout.clearance_too_small',
        'category': 'layout',
        'severity': 'warning',
        'title': 'Clearance между проводниками < 0.3 мм для V > 30 В',
        'recommendation': 'IPC-2221: clearance растёт с напряжением. > 30 В = > 0.4 мм.',
        'when': 'clearance_violations > 0',
        'evidence_fields': ['clearance_violations'],
        'enabled': False,
        'source': 'IPC-2221A clearance',
        'confidence': 0.95,
    },
    {
        'id': 'layout.via_too_small',
        'category': 'layout',
        'severity': 'recommendation',
        'title': 'Via < 0.3 мм — стандартный fab требует > 0.3 мм',
        'recommendation': 'Увеличьте размер via или уточните возможности производителя.',
        'when': 'small_via_count > 0',
        'evidence_fields': ['small_via_count'],
        'enabled': False,
        'source': 'JLCPCB / PCBWay specs',
        'confidence': 0.85,
    },
    {
        'id': 'layout.pad_too_small_for_smd',
        'category': 'layout',
        'severity': 'recommendation',
        'title': 'SMD-pad меньше стандартного для footprint',
        'recommendation': 'Используйте стандартные KiCad/Eagle footprint-библиотеки.',
        'when': 'small_smd_pad_count > 0',
        'evidence_fields': ['small_smd_pad_count'],
        'enabled': False,
        'source': 'IPC-7351B',
        'confidence': 0.8,
    },
    {
        'id': 'layout.silkscreen_overlap',
        'category': 'layout',
        'severity': 'recommendation',
        'title': 'Silkscreen текст перекрывает pads',
        'recommendation': 'Перенесите подписи в свободные зоны.',
        'when': 'silkscreen_overlap_count > 0',
        'evidence_fields': ['silkscreen_overlap_count'],
        'enabled': False,
        'source': 'IPC-A-610 assembly',
        'confidence': 0.8,
    },
    {
        'id': 'layout.no_ground_pour',
        'category': 'layout',
        'severity': 'recommendation',
        'title': 'Нет ground pour (заливки GND)',
        'recommendation': 'Добавьте GND-pour для shielding и тепла.',
        'when': 'has_ground_pour == false and component_count > 5',
        'evidence_fields': ['has_ground_pour'],
        'enabled': False,
        'source': 'Industry layout practice',
        'confidence': 0.7,
    },
    {
        'id': 'layout.no_mounting_holes',
        'category': 'layout',
        'severity': 'recommendation',
        'title': 'Нет монтажных отверстий',
        'recommendation': 'Добавьте 2-4 отверстия M3 для крепления.',
        'when': 'mounting_holes_count == 0',
        'evidence_fields': ['mounting_holes_count'],
        'enabled': False,
        'source': 'Industry assembly',
        'confidence': 0.85,
    },

    # ─── K. STANDARDS COMPLIANCE ──────────────────────────────────────────
    {
        'id': 'compliance.rohs_components',
        'category': 'compliance',
        'severity': 'recommendation',
        'title': 'Компоненты без RoHS-маркировки',
        'recommendation': 'Для коммерческой схемы все компоненты должны быть RoHS-совместимы.',
        'when': 'non_rohs_components > 0',
        'evidence_fields': ['non_rohs_components'],
        'enabled': False,
        'source': 'EU RoHS directive',
        'confidence': 0.8,
    },
    {
        'id': 'compliance.no_emc_filtering',
        'category': 'compliance',
        'severity': 'recommendation',
        'title': 'Нет EMC-фильтрации на питании',
        'recommendation': 'Добавьте common-mode choke + Y-конденсаторы для прохождения EMC-тестов.',
        'when': 'has_power_input == true and emc_filter_present == false',
        'evidence_fields': ['emc_filter_present'],
        'enabled': False,
        'source': 'EN 55032 EMC',
        'confidence': 0.7,
    },
    {
        'id': 'compliance.high_voltage_no_creepage',
        'category': 'compliance',
        'severity': 'error',
        'title': 'Высоковольтные цепи без creepage/clearance',
        'recommendation': 'IEC 60664-1: > 250 В = creepage > 2.5 мм.',
        'when': 'high_voltage_creepage_violations > 0',
        'evidence_fields': ['high_voltage_creepage_violations'],
        'enabled': False,
        'source': 'IEC 60664-1',
        'confidence': 0.95,
    },

    # ─── L. AI-SUGGESTED PATTERNS ─────────────────────────────────────────
    {
        'id': 'ai.suggested_pattern_match',
        'category': 'ai',
        'severity': 'recommendation',
        'title': 'AI распознал паттерн: возможны улучшения',
        'recommendation': 'См. рекомендации AI-ассистента в детальной модалке.',
        'when': 'ai_pattern_matches > 0',
        'evidence_fields': ['ai_pattern_matches'],
        'enabled': False,
        'source': 'DOLG AI rule_ai.py',
        'confidence': 0.55,
    },
    {
        'id': 'ai.anomaly_detection',
        'category': 'ai',
        'severity': 'warning',
        'title': 'AI: схема нетипична для своей категории',
        'recommendation': 'Проверьте — это намеренная инновация или ошибка.',
        'when': 'ai_anomaly_score > 0.7',
        'evidence_fields': ['ai_anomaly_score'],
        'enabled': False,
        'source': 'DOLG AI anomaly',
        'confidence': 0.5,
    },
]


def main():
    with RULES_FILE.open('r', encoding='utf-8') as f:
        data = json.load(f)

    existing_ids = {r['id'] for r in data['rules']}
    print(f'Existing rules: {len(data["rules"])}')

    added = 0
    for new_rule in NEW_RULES:
        if new_rule['id'] in existing_ids:
            continue
        # Унифицируем структуру с существующими
        rule = {
            'id': new_rule['id'],
            'title': new_rule['title'],
            'severity': new_rule['severity'],
            'when': new_rule['when'],
            'evidence_fields': new_rule['evidence_fields'],
            'recommendation': new_rule['recommendation'],
            'confidence': new_rule['confidence'],
            'category': new_rule.get('category', 'general'),
            'enabled': new_rule.get('enabled', False),
            'references': {
                'source_ids': [new_rule.get('source', 'unknown')],
            },
        }
        data['rules'].append(rule)
        added += 1

    data['version'] = '2026.05-expert-v2-100rules'
    data['description'] = (
        f'Расширенный набор детерминированных экспертных правил DOLG ({len(data["rules"])} правил). '
        'Категории: connectivity, power, polarity, rating, topology, signal, bom, simulation, docs, layout, compliance, ai. '
        'Источники: KiCad ERC, IPC-2221A/A-610, ngspice docs, industry datasheet practices, academic papers.'
    )

    with RULES_FILE.open('w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f'Added: {added} new rules')
    print(f'Total: {len(data["rules"])} rules')

    # Stats by category
    cats = {}
    for r in data['rules']:
        c = r.get('category', 'unknown')
        cats[c] = cats.get(c, 0) + 1
    print('By category:')
    for c, n in sorted(cats.items(), key=lambda kv: -kv[1]):
        print(f'  {c}: {n}')

    # Stats by enabled
    enabled = sum(1 for r in data['rules'] if r.get('enabled', False))
    print(f'Enabled (implemented): {enabled}')
    print(f'Planned (not yet implemented): {len(data["rules"]) - enabled}')


if __name__ == '__main__':
    main()
