# Generated by Django 6.0.4 on 2026-05-03 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'Обработка'), ('succeeded', 'Успешно'), ('failed', 'Ошибка'), ('cancelled', 'Отменено'), ('refunded', 'Возвращено')], default='pending', max_length=20)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('yandex', 'Yandex.Kassa'), ('sberbank', 'Sberbank')], default='stripe', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('transaction_id', models.CharField(editable=False, max_length=255, unique=True)),
                ('charge_id', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transaction', to='orders.order')),
            ],
            options={
                'verbose_name': 'Платежная транзакция',
                'verbose_name_plural': 'Платежные транзакции',
                'ordering': ['-created_at'],
            },
        ),
    ]
